services:
  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - modcore_postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    env_file:
      - .env
  
  web:
    build: 
      context: ./src
      dockerfile: ./Dockerfiles/web.dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - postgres
    env_file:
      - .env
    depends_on:
      - postgres

  jobs:
    build:
      context: ./src
      dockerfile: ./Dockerfiles/jobs.dockerfile
    restart: unless-stopped
    links:
      - postgres
    env_file:
      - .env
    depends_on:
      - postgres

  # Shards, these define websocket connections with Discord's gateway.
  # Ensure shard_count is correct in .env!!!
  shard_0:
    build: 
      context: ./src
      dockerfile: ./Dockerfiles/shard.dockerfile
    restart: unless-stopped
    links:
      - postgres
    environment:
      - current_shard=0
    env_file:
      - .env
    depends_on:
      - postgres
      
volumes:
  modcore_postgres:
