services:
  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    shm_size: 256mb
    ports:
      - 5444:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - modcore_postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    env_file:
      - .env
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - modcore_redis:/data

  redis_commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    links:
      - redis
      
volumes:
  modcore_postgres:
  modcore_redis:
