services:
  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - modcore_postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - modcore_redis:/data

  rest_proxy:
    build: 
      context: ./src
      dockerfile: ./Dockerfiles/rest_proxy.dockerfile
    restart: unless-stopped
    expose:
      - "8085"
  
  web:
    build: 
      context: ./src
      dockerfile: ./Dockerfiles/web.dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - postgres
      - rest_proxy
    env_file:
      - .env
    depends_on:
      - postgres
      - rest_proxy

  jobs:
    build:
      context: ./src
      dockerfile: ./Dockerfiles/jobs.dockerfile
    restart: unless-stopped
    links:
      - postgres
      - rest_proxy
    env_file:
      - .env
    depends_on:
      - postgres
      - rest_proxy

  # Shards, these define websocket connections with Discord's gateway.
  # Ensure shard_count is correct in .env!!!
  shard_0:
    build: 
      context: ./src
      dockerfile: ./Dockerfiles/shard.dockerfile
    restart: unless-stopped
    links:
      - postgres
      - rest_proxy
    environment:
      - current_shard=0
    env_file:
      - .env
    depends_on:
      - postgres
      - rest_proxy
      
volumes:
  modcore_postgres:
  modcore_redis:
