//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModCore.Common.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModCore.Common.Language.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Want to contribute?**
        ///Contributions are always welcome at our [GitHub repo](https://github.com/Naamloos/ModCore)..
        /// </summary>
        public static string aboutContribute {
            get {
                return ResourceManager.GetString("aboutContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Donate?**
        ///Currently, ModCore is hosted off my (Naamloos&apos;s) own money. Donations are always welcome over at [Ko-Fi](https://ko-fi.com/naamloos)!.
        /// </summary>
        public static string aboutDonate {
            get {
                return ResourceManager.GetString("aboutDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Main Developer**
        ///[Naamloos](https://github.com/Naamloos).
        /// </summary>
        public static string aboutMainDeveloper {
            get {
                return ResourceManager.GetString("aboutMainDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Special thanks to all of these wonderful v2 contributors:**
        ///{contribs}.
        /// </summary>
        public static string aboutPreviousContribs {
            get {
                return ResourceManager.GetString("aboutPreviousContribs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Welcome to ModCore v3.
        /// </summary>
        public static string aboutWelcome {
            get {
                return ResourceManager.GetString("aboutWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed banning {user}, something went wrong..
        /// </summary>
        public static string banFailure {
            get {
                return ResourceManager.GetString("banFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed banning {user}, but the user was already notified....
        /// </summary>
        public static string banFailureDmAlreadySent {
            get {
                return ResourceManager.GetString("banFailureDmAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were banned from {guild}.
        ///
        ///Reason:
        ///```
        ///{reason}
        ///```
        ///
        ///This server does **not** have appeals enabled..
        /// </summary>
        public static string banNotifyMessage {
            get {
                return ResourceManager.GetString("banNotifyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully banned member {user}. Sent DM: {sentDM|t:yes|t:no}.
        ///
        ///Reason:
        ///```
        ///{reason}
        ///```.
        /// </summary>
        public static string banSuccess {
            get {
                return ResourceManager.GetString("banSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
