// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModCore.Common.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModCore.Common.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241223165848_FixEnabledFieldInWelcomer")]
    partial class FixEnabledFieldInWelcomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseAutoRole", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("role_id")
                        .HasAnnotation("Relational:JsonPropertyName", "role_id");

                    b.HasKey("GuildId", "RoleId");

                    b.ToTable("mcore_autorole");

                    b.HasAnnotation("Relational:JsonPropertyName", "auto_roles");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseBanAppeal", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Relational:JsonPropertyName", "guild_id");

                    b.Property<string>("AppealContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("appeal_content")
                        .HasAnnotation("Relational:JsonPropertyName", "appeal_content");

                    b.HasKey("UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("mcore_appeal");

                    b.HasAnnotation("Relational:JsonPropertyName", "ban_appeals");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseGuild", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal?>("AppealChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("appeal_channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "appeal_channel_id");

                    b.Property<bool>("AutoRoleEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_role_enabled")
                        .HasAnnotation("Relational:JsonPropertyName", "auto_role_enabled");

                    b.Property<int>("EmbedMessageLinks")
                        .HasColumnType("integer")
                        .HasColumnName("embed_message_links_state")
                        .HasAnnotation("Relational:JsonPropertyName", "embed_message_links_state");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasAnnotation("Relational:JsonPropertyName", "last_seen_at");

                    b.Property<decimal?>("LoggingChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("logging_channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "logging_channel_id");

                    b.Property<decimal?>("ModlogChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("modlog_channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "modlog_channel_id");

                    b.Property<decimal?>("NicknameConfirmationChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("nick_confirm_channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "nick_confirm_channel_id");

                    b.Property<bool>("PersistUserNicknames")
                        .HasColumnType("boolean")
                        .HasColumnName("persist_user_nicknames")
                        .HasAnnotation("Relational:JsonPropertyName", "persist_user_nicknames");

                    b.Property<bool>("PersistUserOverrides")
                        .HasColumnType("boolean")
                        .HasColumnName("persist_user_overrides")
                        .HasAnnotation("Relational:JsonPropertyName", "persist_user_overrides");

                    b.Property<bool>("PersistUserRoles")
                        .HasColumnType("boolean")
                        .HasColumnName("persist_user_roles")
                        .HasAnnotation("Relational:JsonPropertyName", "persist_user_roles");

                    b.Property<decimal?>("TicketChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("ticket_channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "ticket_channel_id");

                    b.HasKey("GuildId");

                    b.ToTable("mcore_guild");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseInfraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason")
                        .HasAnnotation("Relational:JsonPropertyName", "reason");

                    b.Property<decimal>("ResponsibleModerator")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("responsible_moderator_id")
                        .HasAnnotation("Relational:JsonPropertyName", "responsible_moderator_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("infraction_type")
                        .HasAnnotation("Relational:JsonPropertyName", "infraction_type");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<bool>("UserNotified")
                        .HasColumnType("boolean")
                        .HasColumnName("user_was_notified")
                        .HasAnnotation("Relational:JsonPropertyName", "user_was_notified");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("mcore_infraction");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseLevelData", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Relational:JsonPropertyName", "guild_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint")
                        .HasColumnName("experience")
                        .HasAnnotation("Relational:JsonPropertyName", "experience");

                    b.Property<DateTimeOffset>("LastGrant")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_xp_grant")
                        .HasAnnotation("Relational:JsonPropertyName", "last_xp_grant");

                    b.HasKey("GuildId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("mcore_leveldata");

                    b.HasAnnotation("Relational:JsonPropertyName", "level_data");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseLevelSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "message_channel_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("levels_enabled")
                        .HasAnnotation("Relational:JsonPropertyName", "enabled");

                    b.Property<bool>("MessagesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("messages_enabled")
                        .HasAnnotation("Relational:JsonPropertyName", "messages_enabled");

                    b.Property<bool>("RedirectMessages")
                        .HasColumnType("boolean")
                        .HasColumnName("redirect_messages")
                        .HasAnnotation("Relational:JsonPropertyName", "redirect_messages");

                    b.HasKey("GuildId");

                    b.ToTable("mcore_levelsettings");

                    b.HasAnnotation("Relational:JsonPropertyName", "level_settings");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseLoggerSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<bool>("LogAvatars")
                        .HasColumnType("boolean")
                        .HasColumnName("log_avatars")
                        .HasAnnotation("Relational:JsonPropertyName", "log_avatars");

                    b.Property<bool>("LogChannels")
                        .HasColumnType("boolean")
                        .HasColumnName("log_channels")
                        .HasAnnotation("Relational:JsonPropertyName", "log_channels");

                    b.Property<bool>("LogGuildEdits")
                        .HasColumnType("boolean")
                        .HasColumnName("log_guild_edit")
                        .HasAnnotation("Relational:JsonPropertyName", "log_guild_edit");

                    b.Property<bool>("LogInvites")
                        .HasColumnType("boolean")
                        .HasColumnName("log_invites")
                        .HasAnnotation("Relational:JsonPropertyName", "log_invites");

                    b.Property<bool>("LogJoins")
                        .HasColumnType("boolean")
                        .HasColumnName("log_joins")
                        .HasAnnotation("Relational:JsonPropertyName", "log_joins");

                    b.Property<bool>("LogMessageEdits")
                        .HasColumnType("boolean")
                        .HasColumnName("log_message_edit")
                        .HasAnnotation("Relational:JsonPropertyName", "log_message_edit");

                    b.Property<bool>("LogNicknames")
                        .HasColumnType("boolean")
                        .HasColumnName("log_nicknames")
                        .HasAnnotation("Relational:JsonPropertyName", "log_nicknames");

                    b.Property<bool>("LogRoleAssignment")
                        .HasColumnType("boolean")
                        .HasColumnName("log_role_assign")
                        .HasAnnotation("Relational:JsonPropertyName", "log_role_assign");

                    b.Property<bool>("LogRoleEdits")
                        .HasColumnType("boolean")
                        .HasColumnName("log_role_edit")
                        .HasAnnotation("Relational:JsonPropertyName", "log_role_edit");

                    b.Property<decimal?>("LoggerChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("logger_channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "logger_channel_id");

                    b.HasKey("GuildId");

                    b.ToTable("mcore_logger_settings");

                    b.HasAnnotation("Relational:JsonPropertyName", "logger_settings");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseNicknameState", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname")
                        .HasAnnotation("Relational:JsonPropertyName", "nickname");

                    b.HasKey("GuildId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("mcore_nickname_state");

                    b.HasAnnotation("Relational:JsonPropertyName", "nickname_states");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseOverrideState", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "channel_id");

                    b.Property<long>("AllowedPermissions")
                        .HasColumnType("bigint")
                        .HasColumnName("allowed")
                        .HasAnnotation("Relational:JsonPropertyName", "allowed");

                    b.Property<long>("DeniedPermissions")
                        .HasColumnType("bigint")
                        .HasColumnName("denied")
                        .HasAnnotation("Relational:JsonPropertyName", "denied");

                    b.HasKey("GuildId", "UserId", "ChannelId");

                    b.HasIndex("UserId");

                    b.ToTable("mcore_override_state");

                    b.HasAnnotation("Relational:JsonPropertyName", "override_states");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseRoleMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CreatorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("creator_id")
                        .HasAnnotation("Relational:JsonPropertyName", "creator_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("mcore_rolemenu");

                    b.HasAnnotation("Relational:JsonPropertyName", "role_menus");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseRoleMenuRole", b =>
                {
                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("role_id")
                        .HasAnnotation("Relational:JsonPropertyName", "role_id");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_id");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("mcore_rolemenu_role");

                    b.HasAnnotation("Relational:JsonPropertyName", "roles");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseRoleState", b =>
                {
                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("role_id")
                        .HasAnnotation("Relational:JsonPropertyName", "role_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("RoleId", "UserId", "GuildId");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("mcore_role_state");

                    b.HasAnnotation("Relational:JsonPropertyName", "role_states");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseStarboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "channel_id");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emoji")
                        .HasAnnotation("Relational:JsonPropertyName", "emoji");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled")
                        .HasAnnotation("Relational:JsonPropertyName", "enabled");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<int>("MinimumReactions")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_reactions")
                        .HasAnnotation("Relational:JsonPropertyName", "minimum_reactions");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("mcore_starboard");

                    b.HasAnnotation("Relational:JsonPropertyName", "starboards");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseStarboardItem", b =>
                {
                    b.Property<long>("StarboardId")
                        .HasColumnType("bigint")
                        .HasColumnName("starboard_id")
                        .HasAnnotation("Relational:JsonPropertyName", "starboard_id");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id")
                        .HasAnnotation("Relational:JsonPropertyName", "message_id");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "channel_id");

                    b.Property<decimal>("StargazerId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("stargazer_id")
                        .HasAnnotation("Relational:JsonPropertyName", "stargazer_id");

                    b.Property<decimal>("AuthorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("author_id")
                        .HasAnnotation("Relational:JsonPropertyName", "author_id");

                    b.Property<decimal>("BoardMessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("board_message_id")
                        .HasAnnotation("Relational:JsonPropertyName", "board_message_id");

                    b.HasKey("StarboardId", "MessageId", "ChannelId", "StargazerId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("StargazerId");

                    b.ToTable("mcore_starboard_item");

                    b.HasAnnotation("Relational:JsonPropertyName", "starred_items");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AuthorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("author_id")
                        .HasAnnotation("Relational:JsonPropertyName", "author_id");

                    b.Property<decimal?>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content")
                        .HasAnnotation("Relational:JsonPropertyName", "content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifed_at")
                        .HasAnnotation("Relational:JsonPropertyName", "modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GuildId");

                    b.ToTable("mcore_tag");

                    b.HasAnnotation("Relational:JsonPropertyName", "tags");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseTagHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content")
                        .HasAnnotation("Relational:JsonPropertyName", "content");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("mcore_tag_history");

                    b.HasAnnotation("Relational:JsonPropertyName", "history");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AuthorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("author_id")
                        .HasAnnotation("Relational:JsonPropertyName", "author_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<decimal?>("TicketThreadId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("ticket_thread_id")
                        .HasAnnotation("Relational:JsonPropertyName", "ticket_thread_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GuildId");

                    b.ToTable("mcore_ticket");

                    b.HasAnnotation("Relational:JsonPropertyName", "opened_tickets");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseTimer", b =>
                {
                    b.Property<long>("TimerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("timer_id")
                        .HasAnnotation("Relational:JsonPropertyName", "timer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TimerId"));

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data")
                        .HasAnnotation("Relational:JsonPropertyName", "data");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Relational:JsonPropertyName", "guild_id");

                    b.Property<int>("ShardId")
                        .HasColumnType("integer")
                        .HasColumnName("shard_id");

                    b.Property<DateTimeOffset>("TriggersAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trigger_at")
                        .HasAnnotation("Relational:JsonPropertyName", "trigger_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("TimerId");

                    b.ToTable("mcore_timers");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseUser", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.HasKey("UserId");

                    b.ToTable("mcore_user");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseWelcomeSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id")
                        .HasAnnotation("Relational:JsonPropertyName", "channel_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled")
                        .HasAnnotation("Relational:JsonPropertyName", "enabled");

                    b.Property<string>("WelcomeMessageJson")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("welcome_message_json")
                        .HasAnnotation("Relational:JsonPropertyName", "welcome_message_json");

                    b.HasKey("GuildId");

                    b.ToTable("mcore_welcomer");

                    b.HasAnnotation("Relational:JsonPropertyName", "welcome_settings");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseAutoRole", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("AutoRoles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseBanAppeal", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("BanAppeals")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModCore.Common.Database.Entities.DatabaseUser", "User")
                        .WithMany("BanAppeals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseInfraction", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("Infractions")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseLevelData", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("LevelData")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModCore.Common.Database.Entities.DatabaseUser", "User")
                        .WithMany("LevelData")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseLevelSettings", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithOne("LevelSettings")
                        .HasForeignKey("ModCore.Common.Database.Entities.DatabaseLevelSettings", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseLoggerSettings", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithOne("LoggerSettings")
                        .HasForeignKey("ModCore.Common.Database.Entities.DatabaseLoggerSettings", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseNicknameState", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("NicknameStates")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModCore.Common.Database.Entities.DatabaseUser", "User")
                        .WithMany("NicknameStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseOverrideState", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("OverrideStates")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModCore.Common.Database.Entities.DatabaseUser", "User")
                        .WithMany("OverrideStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseRoleMenu", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("RoleMenus")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseRoleMenuRole", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseRoleMenu", "Menu")
                        .WithMany("Roles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseRoleState", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("RoleStates")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModCore.Common.Database.Entities.DatabaseUser", "User")
                        .WithMany("RoleStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseStarboard", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("Starboards")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseStarboardItem", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseUser", "Author")
                        .WithMany("StarboardItems")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModCore.Common.Database.Entities.DatabaseStarboard", "Starboard")
                        .WithMany("Items")
                        .HasForeignKey("StarboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModCore.Common.Database.Entities.DatabaseUser", "Stargazer")
                        .WithMany("StarredItems")
                        .HasForeignKey("StargazerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Starboard");

                    b.Navigation("Stargazer");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseTag", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseUser", "Author")
                        .WithMany("Tags")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("Tags")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseTagHistory", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseTag", "Tag")
                        .WithMany("History")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseTicket", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseUser", "Author")
                        .WithMany("Tickets")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithMany("Tickets")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseWelcomeSettings", b =>
                {
                    b.HasOne("ModCore.Common.Database.Entities.DatabaseGuild", "Guild")
                        .WithOne("WelcomeSettings")
                        .HasForeignKey("ModCore.Common.Database.Entities.DatabaseWelcomeSettings", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseGuild", b =>
                {
                    b.Navigation("AutoRoles");

                    b.Navigation("BanAppeals");

                    b.Navigation("Infractions");

                    b.Navigation("LevelData");

                    b.Navigation("LevelSettings")
                        .IsRequired();

                    b.Navigation("LoggerSettings")
                        .IsRequired();

                    b.Navigation("NicknameStates");

                    b.Navigation("OverrideStates");

                    b.Navigation("RoleMenus");

                    b.Navigation("RoleStates");

                    b.Navigation("Starboards");

                    b.Navigation("Tags");

                    b.Navigation("Tickets");

                    b.Navigation("WelcomeSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseRoleMenu", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseStarboard", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseTag", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("ModCore.Common.Database.Entities.DatabaseUser", b =>
                {
                    b.Navigation("BanAppeals");

                    b.Navigation("LevelData");

                    b.Navigation("NicknameStates");

                    b.Navigation("OverrideStates");

                    b.Navigation("RoleStates");

                    b.Navigation("StarboardItems");

                    b.Navigation("StarredItems");

                    b.Navigation("Tags");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
