using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using DSharpPlus;
using DSharpPlus.Entities;
using DSharpPlus.EventArgs;
using ModCore.Logic;

namespace ModCore.Listeners
{
    public static class LinkRemover
    {
        [AsyncListener(EventTypes.MessageCreated)]
        public static async Task RemoveSuspiciousLinks(ModCoreShard bot, MessageCreateEventArgs e)
        {
            if ((e.Channel.PermissionsFor(e.Author as DiscordMember) & Permissions.ManageMessages) != 0) return;
            
            if (bot.Settings.BlockInvites)
            {
                if (LinkRemoverConstants.InviteLinkRegex.Match(e.Message.Content).Success)
                {
                    await e.Message.DeleteAsync("Discovered invite and deleted message");
                }
            }
            
            if (bot.Settings.BlockIpLoggers)
            {
                if (LinkRemoverConstants.IpLoggerRegex.Match(e.Message.Content).Success)
                {
                    await e.Message.DeleteAsync("Discovered IP logger site and deleted message");
                }
            }
            
            if (bot.Settings.BlockBooters)
            {
                if (LinkRemoverConstants.BooterRegex.Match(e.Message.Content).Success)
                {
                    await e.Message.DeleteAsync("Discovered Booter/DDoS site and deleted message");
                }
            }

            if (bot.Settings.BlockUrlShorteners)
            {
                await MatchUrlShorteners(e);
            }
        }

        // separate method to avoid loading the url shortener class (and all the strings inside) if not necessary.
        // this saves a lot of memory if you don't care about URL shorteners.
        private static async Task MatchUrlShorteners(MessageCreateEventArgs e)
        {
            var match = UrlShortenerConstants.UrlShortenerRegex.Match(e.Message.Content);
            if (match.Success)
            {
                await e.Message.DeleteAsync($"Discovered URL shortener and deleted message. Info: {match.Groups[0].Value}");
            }
        }
    }

    public static class LinkRemoverConstants
    {
        /// <summary>
        /// Regex to match invite links.
        /// </summary>
        public static readonly Regex InviteLinkRegex = new Regex(@"discord(\.gg|app\.com\/invite)\/.+");

        /// <summary>
        /// Regex to match IP logger sites.
        /// </summary>
        public static readonly Regex IpLoggerRegex =
            CreateLiteralRegex(
                "iplogger.org",
                "2no.co",
                "ezstat.ru",
                "iplogger.info",
                "02ip.ru",
                "iplo.ru",
                "iplis.ru",
                "iplogger.com",
                "iplogger.ru",
                "iplogger.org",
                "pgrabber.ru",
                "grabify.link",
                "ip.jlynx.net",
                "deviantartt.ml",
                "dropboxx.lm ",
                "gyazoo.ga",
                "linkit.cf",
                "printscr.ga",
                "youutube.gq",
                "strawpoll.ga",
                "xxox.co.uk",
                "leakforum.ga",
                "prntsc.cf",
                "deviantartt.ga",
                "dropboxx.ga",
                "dropboxx.cf",
                "strawpolll.ga",
                "twitte.ga",
                "bvog.com",
                "hondachat.com",
                "youramonkey.com",
                "blasze.tk",
                "myiptest.com/img.php",
                "ip-grabber.com",
                "imgurl.us",
                "skypegrab.net",
                "sciencefuture.tk",
                "stresser.science",
                "imageshack.ml",
                "viphackforums.xyz",
                "gtadb.net",
                "fotocerdas.com",
                "parlament.usa.cc",
                "hs.vc",
                "community.hackersclub.net",
                "login.anal-porn.info",
                "paypal.sellbitcoins.com",
                "panel.teamspeak.bz	",
                "files.uploads.ws",
                "cubeupload.com",
                "media.appspot.com",
                "hackfȯrums.net",
                "hackfȯrums.com",
                "imgúr.com",
                "battlė.net",
                "dank.host",
                "r1p.pw",
                "webprofile.me",
                "anonymousforum.pw",
                "ts3free.top",
                "viphackforum.xyz",
                "bbcnews.today",
                "privatexmpp.me",
                "topstreaming.us",
                "topcdn.biz",
                "postimage.co",
                "hackernews.online",
                "hdblog.tech",
                "sexy18.webcam",
                "dropbox.desi",
                "hostingonline.desi",
                "freeanonymous.host",
                "ampnode.host",
                "spoofing.host",
                "cubeupload.xyz",
                "exploit-db.xyz",
                "gyazoo.xyz",
                "ipddoser.xyz",
                "skypecracker.xyz",
                "ipsnatcher.com",
                "skidpaste.org",
                "cloudfsx.com",
                "ps3cfw.com",
                // third party
                "aruljohn.com/widget/zip/",
                "aruljohn.com/widget/ip/");
    
            /// <summary>
            /// Regex to match booter/DDoS as a Service sites.
            /// </summary>
            public static readonly Regex BooterRegex =
                CreateLiteralRegex(
                    "orcahub.com",
                    "vbooter.org",
                    "orboot.pw",
                    "ddos.city",
                    "restresser.com",
                    "networkstresser.com",
                    "vdos-s.com",
                    "oxystress.eu",
                    "freebooter.pro",
                    "bootyou.net",
                    "critical-boot.com");

        internal static Regex CreateLiteralRegex(params string[] items)
        {
            return new Regex($@"({string.Join('|', items.Select(Regex.Escape))})");
        }
    }

    // use a separate class to avoid class loader bloat
    public static class UrlShortenerConstants
    {
        public static readonly ImmutableDictionary<string, string> UrlShorteners = new Dictionary<string, string>()
        {
            ["jesais.fr"] = "http://www.jelev.eu/accueil.php",
            ["aelita.fr"] = "http://www.jelev.eu/accueil.php",
            ["jelev.eu"] = "http://www.jelev.eu/accueil.php",
            ["jesais.fr"] = "http://www.jelev.eu/accueil.php",
            ["jtefaisla.biz"] = "http://www.jelev.eu/accueil.php",
            ["lacheun.com"] = "http://www.jelev.eu/accueil.php",
            ["lyoko.eu"] = "http://www.jelev.eu/accueil.php",
            ["mattemon.info"] = "http://www.jelev.eu/accueil.php",
            ["monbe.be"] = "http://www.jelev.eu/accueil.php",
            ["oueb.eu"] = "http://www.jelev.eu/accueil.php",
            ["pourle.net"] = "http://www.jelev.eu/accueil.php",
            ["xana.fr"] = "http://www.jelev.eu/accueil.php",
            ["smll.me"] = "http://smll.me",
            ["06.hk"] = "http://urlshortener.org",
            ["kwik.to"] = "http://sitelutions.com",
            ["0rz.tw"] = "http://0rz.tw",
            ["10.rs"] = "http://urlshortener.org",
            ["1iny.com"] = "http://urlshortener.org",
            ["1kh.de"] = "http://urlshortener.org",
            ["1link.in"] = "http://longurl.org/services",
            ["1tja.com"] = "N/A",
            ["1url.com"] = "http://www.mrbup.com",
            ["2.gp"] = "http://longurl.org/services",
            ["2big.at"] = "http://urlshortener.org",
            ["2tr.net"] = "http://urlshortener.org",
            ["2tu.us"] = "http://urlshortener.org",
            ["3.ly"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["307.to"] = "http://longurl.org/services",
            ["4ms.me"] = "http://longurl.org/services",
            ["4nu.net"] = "N/A",
            ["4sq.com"] = "http://longurl.org/services",
            ["4url.cc"] = "http://longurl.org/services",
            ["55c.cc"] = "http://urlshortener.org",
            ["6t4.us"] = "http://urlshortener.org",
            ["6url.com"] = "http://longurl.org/services",
            ["7.ly"] = "http://longurl.org/services",
            ["7les.com"] = "http://urlshortener.org",
            ["98.to"] = "http://98.to/tc/home.asp",
            ["a.gg"] = "http://longurl.org/services",
            ["a.nf"] = "http://longurl.org/services",
            ["a.nf"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["aa.cx"] = "http://longurl.org/services",
            ["abcurl.net"] = "http://longurl.org/services",
            ["abe5.com"] = "http://urlshortener.org",
            ["ad.vu"] = "http://longurl.org/services",
            ["adf.ly"] = "http://longurl.org/services",
            ["adjix.com"] = "http://longurl.org/services",
            ["afx.cc"] = "http://longurl.org/services",
            ["all.fuseurl.com"] = "http://longurl.org/services",
            ["alturl.com"] = "http://longurl.org/services",
            ["amzn.to"] = "http://longurl.org/services",
            ["ao.co.za"] = "http://urlshortener.org",
            ["apu.sh"] = "http://urlshortener.org",
            ["ar.gy"] = "http://longurl.org/services",
            ["arm.in"] = "http://urlshortener.org",
            ["arst.ch"] = "http://longurl.org/services",
            ["atu.ca"] = "http://longurl.org/services",
            ["ax.ag"] = "http://urlshortener.org",
            ["azc.cc"] = "http://longurl.org/services",
            ["b00b.tk"] = "http://urlshortener.org",
            ["b23.ru"] = "http://longurl.org/services",
            ["b2l.me"] = "http://urlshortener.org",
            ["bacn.me"] = "http://longurl.org/services",
            ["bcool.bz"] = "http://longurl.org/services",
            ["biglnk.com"] = "http://urlshortener.org",
            ["binged.it"] = "http://longurl.org/services",
            ["bit.ly"] = "http://longurl.org/services",
            ["bizj.us"] = "http://longurl.org/services",
            ["bizy.be"] = "http://urlshortener.org",
            ["bizz.cc"] = "http://urlshortener.org",
            ["bloat.me"] = "http://longurl.org/services",
            ["bpt.st"] = "http://urlshortener.org",
            ["br.st"] = "http://urlshortener.org",
            ["bravo.ly"] = "http://longurl.org/services",
            ["bsa.ly"] = "http://longurl.org/services",
            ["budurl.com"] = "http://longurl.org/services",
            ["canurl.com"] = "http://urlshortener.org",
            ["cd4.me"] = "http://urlshortener.org",
            ["checkthislink.com"] = "http://urlshortener.org",
            ["chilp.it"] = "http://longurl.org/services",
            ["chrst.ph"] = "http://urlshortener.org",
            ["chs.mx"] = "http://urlshortener.org",
            ["chzb.gr"] = "http://longurl.org/services",
            ["cl.lk"] = "http://longurl.org/services",
            ["clck.ru"] = "http://urlshortener.org",
            ["cli.gs"] = "http://urlshortener.org",
            ["cliccami.info"] = "http://longurl.org/services",
            ["clickthru.ca"] = "http://longurl.org/services",
            ["clockurl.com"] = "http://urlshortener.org",
            ["clop.in"] = "http://urlshortener.org",
            ["coge.la"] = "N/A",
            ["conta.cc"] = "http://longurl.org/services",
            ["cort.as"] = "http://urlshortener.org",
            ["cot.ag"] = "http://longurl.org/services",
            ["cr.am"] = "http://urlshortener.org",
            ["crks.me"] = "http://longurl.org/services",
            ["cru.ms"] = "http://urlshortener.org",
            ["ctvr.us"] = "http://longurl.org/services",
            ["cut.by"] = "http://urlshortener.org",
            ["cutt.us"] = "http://longurl.org/services",
            ["d3c.co"] = "N/A",
            ["dai.ly"] = "http://longurl.org/services",
            ["decenturl.com"] = "http://longurl.org/services",
            ["delivr.com"] = "http://urlshortener.org",
            ["devnull.at"] = "http://urlshortener.org",
            ["df9.net"] = "http://urlshortener.org",
            ["dfl8.me"] = "http://urlshortener.org",
            ["dickensurl.com"] = "http://urlshortener.org",
            ["digbig.com"] = "http://longurl.org/services",
            ["digg.com"] = "http://longurl.org/services",
            ["disq.us"] = "http://longurl.org/services",
            ["dld.bz"] = "http://longurl.org/services",
            ["dlvr.it"] = "http://longurl.org/services",
            ["do.my"] = "http://longurl.org/services",
            ["doiop.com"] = "http://urlshortener.org",
            ["dopen.us"] = "http://longurl.org/services",
            ["drv2.com"] = "http://urlshortener.org",
            ["dwarfurl.com"] = "http://urlshortener.org",
            ["dz.ly"] = "http://urlshortener.org",
            ["earlme.com"] = "http://urlshortener.org",
            ["easyurl.net"] = "http://longurl.org/services",
            ["eepurl.com"] = "http://longurl.org/services",
            ["eg3.net"] = "http://urlshortener.org",
            ["ekey.us"] = "http://urlshortener.org",
            ["elurl.com"] = "http://urlshortener.org",
            ["eweri.com"] = "http://longurl.org/services",
            ["fa.by"] = "http://longurl.org/services",
            ["fat.ly"] = "http://urlshortener.org",
            ["fav.me"] = "http://longurl.org/services",
            ["fb.me"] = "http://longurl.org/services",
            ["fbshare.me"] = "http://longurl.org/services",
            ["ff.im"] = "http://longurl.org/services",
            ["fff.to"] = "http://fff.to/",
            ["fhurl.com"] = "http://urlshortener.org",
            ["fire.to"] = "http://longurl.org/services",
            ["firsturl.de"] = "http://longurl.org/services",
            ["firsturl.net"] = "http://longurl.org/services",
            ["flib.in"] = "http://urlshortener.org",
            ["flic.kr"] = "http://longurl.org/services",
            ["flq.us"] = "http://urlshortener.org",
            ["fly2.ws"] = "http://longurl.org/services",
            ["flyfrm.com"] = "N/A",
            ["fon.gs"] = "http://longurl.org/services",
            ["forit.org"] = "http://urlshortener.org",
            ["forwarding.clockwatchers.com"] = "http://forwarding.clockwatchers.com",
            ["freak.to"] = "http://longurl.org/services",
            ["fuseurl.com"] = "http://longurl.org/services",
            ["fuzzy.to"] = "http://longurl.org/services",
            ["fwd4.me"] = "http://urlshortener.org",
            ["fwib.net"] = "http://longurl.org/services",
            ["g.ro.lt"] = "http://urlshortener.org",
            ["gentleurl.net"] = "http://urlshortener.org",
            ["gizmo.do"] = "http://longurl.org/services",
            ["gl.am"] = "http://urlshortener.org",
            ["gli.im"] = "N/A",
            ["go.9nl.com"] = "http://longurl.org/services",
            ["go.ign.com"] = "http://longurl.org/services",
            ["go.usa.gov"] = "http://longurl.org/services",
            ["go2.st"] = "http://urlshortener.org",
            ["goo.gl"] = "http://longurl.org/services",
            ["good.ly"] = "http://urlshortener.org",
            ["gop.am"] = "http://urlshortener.org",
            ["goshrink.com"] = "http://longurl.org/services",
            ["gsfn.info"] = "N/A",
            ["gu.ma"] = "http://urlshortener.org",
            ["gurl.es"] = "http://urlshortener.org",
            ["hex.io"] = "http://longurl.org/services",
            ["hi2.com"] = "N/A",
            ["hiderefer.com"] = "http://longurl.org/services",
            ["hmm.ph"] = "http://longurl.org/services",
            ["hop.im"] = "http://urlshortener.org",
            ["hostviet.biz"] = "http://urlshortener.org",
            ["hotshorturl.com"] = "http://urlshortener.org",
            ["hotshr.com"] = "http://urlshortener.org",
            ["href.in"] = "http://longurl.org/services",
            ["href.to"] = "http://urlshortener.org",
            ["hsblinks.com"] = "http://longurl.org/services",
            ["htxt.it"] = "http://longurl.org/services",
            ["hub.tm"] = "http://urlshortener.org",
            ["huff.to"] = "http://longurl.org/services",
            ["hulu.com"] = "http://longurl.org/services",
            ["hurl.me"] = "http://urlshortener.org",
            ["hurl.ws"] = "http://urlshortener.org",
            ["icanhaz.com"] = "http://urlshortener.org",
            ["idek.net"] = "http://urlshortener.org",
            ["ikr.me"] = "http://urlshortener.org",
            ["ilix.in"] = "http://longurl.org/services",
            ["imfy.us"] = "http://urlshortener.org",
            ["in2s.us"] = "http://urlshortener.org",
            ["inturl.com"] = "http://urlshortener.org",
            ["ion.so"] = "N/A",
            ["is.gd"] = "http://urlshortener.org",
            ["it1.nl"] = "http://urlshortener.org",
            ["ito.mx"] = "http://urlshortener.org",
            ["its.my"] = "http://longurl.org/services",
            ["ix.lt"] = "http://longurl.org/services",
            ["j.mp"] = "http://longurl.org/services",
            ["jijr.com"] = "http://longurl.org/services",
            ["ju.nu"] = "http://urlshortener.org",
            ["kaano.info"] = "http://urlshortener.org",
            ["ki.tl"] = "http://urlshortener.org",
            ["kissa.be"] = "http://urlshortener.org",
            ["kiwiurl.com"] = "http://urlshortener.org",
            ["kl.am"] = "http://urlshortener.org",
            ["klck.me"] = "http://longurl.org/services",
            ["korta.nu"] = "http://urlshortener.org",
            ["krunchd.com"] = "http://urlshortener.org",
            ["krz.ch"] = "http://urlshortener.org",
            ["ks.gs"] = "N/A",
            ["kuerzer.de"] = "http://urlshortener.org",
            ["kxk.me"] = "http://urlshortener.org",
            ["l.pr"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["l9k.net"] = "http://longurl.org/services",
            ["lamped.co.uk"] = "http://urlshortener.org",
            ["lat.ms"] = "http://longurl.org/services",
            ["lawurl.com"] = "N/A",
            ["lb.vg"] = "http://urlshortener.org",
            ["liip.to"] = "http://longurl.org/services",
            ["liltext.com"] = "http://longurl.org/services",
            ["linkasa.com"] = "http://urlshortener.org",
            ["linkbee.com"] = "http://urlshortener.org",
            ["linkbun.ch"] = "http://longurl.org/services",
            ["linkfrog.net"] = "http://urlshortener.org",
            ["linkpeak.com"] = "http://urlshortener.org",
            ["liteurl.com"] = "http://urlshortener.org",
            ["liurl.cn"] = "http://urlshortener.org",
            ["lllll.im"] = "N/A",
            ["ln-s.net"] = "http://longurl.org/services",
            ["ln-s.ru"] = "http://longurl.org/services",
            ["lnk.by"] = "http://urlshortener.org",
            ["lnk.gd"] = "http://longurl.org/services",
            ["lnk.ms"] = "http://longurl.org/services",
            ["lnkd.in"] = "http://longurl.org/services",
            ["lnkurl.com"] = "http://longurl.org/services",
            ["lru.jp"] = "http://longurl.org/services",
            ["lt.tl"] = "http://longurl.org/services",
            ["lurl.no"] = "http://longurl.org/services",
            ["lymme.com"] = "http://urlshortener.org",
            ["macte.ch"] = "http://longurl.org/services",
            ["mash.to"] = "http://longurl.org/services",
            ["memurl.com"] = "http://urlshortener.org",
            ["merky.de"] = "http://longurl.org/services",
            ["metamark.net"] = "http://urlshortener.org",
            ["migre.me"] = "http://longurl.org/services",
            ["minify.me"] = "http://urlshortener.org",
            ["minilien.com"] = "http://urlshortener.org",
            ["minilink.org"] = "http://urlshortener.org",
            ["miniurl.com"] = "http://longurl.org/services",
            ["minu.me"] = "http://urlshortener.org",
            ["minurl.fr"] = "http://longurl.org/services",
            ["minyurl.net"] = "http://urlshortener.org",
            ["mke.me"] = "http://longurl.org/services",
            ["moby.to"] = "http://longurl.org/services",
            ["monbe.be"] = "N/A",
            ["moourl.com"] = "http://urlshortener.org",
            ["mrte.ch"] = "http://longurl.org/services",
            ["multiurl.com"] = "http://urlshortener.org",
            ["mylnk.us"] = "http://urlshortener.org",
            ["myloc.me"] = "http://longurl.org/services",
            ["myurl.in"] = "http://urlshortener.org",
            ["myurlz.com"] = "http://urlshortener.org",
            ["n.pr"] = "http://longurl.org/services",
            ["nbc.co"] = "http://longurl.org/services",
            ["nblo.gs"] = "http://longurl.org/services",
            ["ncane.com"] = "http://urlshortener.org",
            ["ne8.org"] = "http://urlshortener.org",
            ["netnet.me"] = "http://urlshortener.org",
            ["ni2.in"] = "http://urlshortener.org",
            ["ninjalink.com"] = "http://urlshortener.org",
            ["niy.me"] = "N/A",
            ["nn.nf"] = "http://longurl.org/services",
            ["no1.in"] = "http://urlshortener.org",
            ["normalurl.com"] = "http://urlshortener.org",
            ["not.my"] = "http://longurl.org/services",
            ["notlong.com"] = "http://urlshortener.org",
            ["nsfw.in"] = "http://longurl.org/services",
            ["nutshellurl.com"] = "http://longurl.org/services",
            ["nuurl.us"] = "http://urlshortener.org",
            ["nxy.in"] = "http://longurl.org/services",
            ["nyti.ms"] = "http://longurl.org/services",
            ["nznet.info"] = "N/A",
            ["o-x.fr"] = "http://urlshortener.org",
            ["oc1.us"] = "http://longurl.org/services",
            ["ohurl.com"] = "http://urlshortener.org",
            ["om.ly"] = "http://longurl.org/services",
            ["omf.gd"] = "http://longurl.org/services",
            ["omoikane.net"] = "http://longurl.org/services",
            ["on.cnn.com"] = "http://longurl.org/services",
            ["on.mktw.net"] = "http://longurl.org/services",
            ["onforb.es"] = "http://longurl.org/services",
            ["orkurl.com"] = "http://urlshortener.org",
            ["orz.se"] = "http://longurl.org/services",
            ["ow.ly"] = "http://urlshortener.org",
            ["p.gs"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["p.ly"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["parv.us"] = "http://urlshortener.org",
            ["pic.gd"] = "http://urlshortener.org",
            ["picsorlinks.com"] = "http://urlshortener.org",
            ["ping.fm"] = "http://longurl.org/services",
            ["piurl.com"] = "http://urlshortener.org",
            ["pli.gs"] = "http://longurl.org/services",
            ["pnt.me"] = "http://urlshortener.org",
            ["politi.co"] = "http://longurl.org/services",
            ["ponyurl.com"] = "http://urlshortener.org",
            ["post.ly"] = "http://longurl.org/services",
            ["pp.gg"] = "http://longurl.org/services",
            ["pr0n.net"] = "http://urlshortener.org",
            ["profile.to"] = "http://longurl.org/services",
            ["ptiturl.com"] = "http://urlshortener.org",
            ["pub.vitrue.com"] = "http://longurl.org/services",
            ["pwr.com"] = "http://urlshortener.org",
            ["qlnk.net"] = "http://urlshortener.org",
            ["qte.me"] = "http://longurl.org/services",
            ["qu.tc"] = "http://longurl.org/services",
            ["qurlyq.com"] = "http://urlshortener.org",
            ["quu.nu"] = "http://urlshortener.org",
            ["qwer.org"] = "http://urlshortener.org",
            ["qwx.si"] = "http://urlshortener.org",
            ["qy.fi"] = "http://longurl.org/services",
            ["r.im"] = "http://longurl.org/services",
            ["rb6.me"] = "http://urlshortener.org",
            ["rcez.info"] = "http://urlshortener.org",
            ["rde.me"] = "http://urlshortener.org",
            ["read.bi"] = "http://longurl.org/services",
            ["readthis.ca"] = "http://longurl.org/services",
            ["reallytinyurl.com"] = "http://longurl.org/services",
            ["redir.ec"] = "http://longurl.org/services",
            ["redir.ec"] = "http://urlshortener.org",
            ["redirects.ca"] = "http://longurl.org/services",
            ["redirx.com"] = "http://urlshortener.org",
            ["relurl.com"] = "http://urlshortener.org",
            ["retwt.me"] = "http://urlshortener.org",
            ["ri.ms"] = "http://longurl.org/services",
            ["rickroll.it"] = "http://longurl.org/services",
            ["riz.gd"] = "http://longurl.org/services",
            ["rt.nu"] = "http://longurl.org/services",
            ["ru.ly"] = "http://longurl.org/services",
            ["rubyurl.com"] = "http://longurl.org/services",
            ["rurl.org"] = "http://longurl.org/services",
            ["rww.tw"] = "http://longurl.org/services",
            ["s4c.in"] = "http://longurl.org/services",
            ["s7y.us"] = "http://urlshortener.org",
            ["safe.mn"] = "http://longurl.org/services",
            ["sameurl.com"] = "http://longurl.org/services",
            ["scrnch.me"] = "http://urlshortener.org",
            ["sdut.us"] = "http://longurl.org/services",
            ["sendtourl.com"] = "N/A",
            ["shar.es"] = "http://longurl.org/services",
            ["shink.de"] = "http://longurl.org/services",
            ["sho.li"] = "http://urlshortener.org",
            ["shoor.tk"] = "N/A",
            ["shorl.com"] = "http://urlshortener.org",
            ["short.ie"] = "http://longurl.org/services",
            ["short.to"] = "http://urlshortener.org",
            ["shorten.ws"] = "http://urlshortener.org",
            ["shortlinks.co.uk"] = "http://longurl.org/services",
            ["shortna.me"] = "http://urlshortener.org",
            ["shortner.com"] = "http://urlshortener.org",
            ["shorturl.com"] = "http://longurl.org/services",
            ["shout.to"] = "http://longurl.org/services",
            ["show.my"] = "http://longurl.org/services",
            ["shrinkify.com"] = "http://longurl.org/services",
            ["shrinkr.com"] = "http://longurl.org/services",
            ["shrt.fr"] = "http://longurl.org/services",
            ["shrt.st"] = "http://longurl.org/services",
            ["shrten.com"] = "http://longurl.org/services",
            ["shrunkin.com"] = "http://longurl.org/services",
            ["shrvl.com"] = "http://urlshortener.org",
            ["shw.me"] = "http://urlshortener.org",
            ["simurl.com"] = "http://longurl.org/services",
            ["simurl.com"] = "http://urlshortener.org",
            ["sl.ly"] = "http://urlshortener.org",
            ["slate.me"] = "http://longurl.org/services",
            ["slnk.me"] = "http://urlshortener.org",
            ["smal.ly"] = "http://urlshortener.org",
            ["smallr.com"] = "http://urlshortener.org",
            ["smlurl.info"] = "N/A",
            ["smrls.tk"] = "http://urlshortener.org",
            ["smsh.me"] = "http://longurl.org/services",
            ["smurl.lv"] = "http://urlshortener.org",
            ["smurl.name"] = "http://longurl.org/services",
            ["sn.im"] = "http://longurl.org/services",
            ["snipr.com"] = "http://longurl.org/services",
            ["snipurl.com"] = "http://urlshortener.org",
            ["snurl.com"] = "http://longurl.org/services",
            ["sp2.ro"] = "http://urlshortener.org",
            ["spedr.com"] = "http://longurl.org/services",
            ["sqze.it"] = "http://long-shore.com/expand",
            ["sra.li"] = "N/A",
            ["srnk.it"] = "http://urlshortener.org",
            ["srnk.net"] = "http://longurl.org/services",
            ["srs.li"] = "http://longurl.org/services",
            ["starturl.com"] = "http://urlshortener.org",
            ["sturly.com"] = "http://urlshortener.org",
            ["su.pr"] = "http://urlshortener.org",
            ["surl.co.uk"] = "http://longurl.org/services",
            ["surl.co.uk"] = "http://urlshortener.org",
            ["surl.hu"] = "http://longurl.org/services",
            ["t.co"] = "http://longurl.org/services",
            ["t.lh.com"] = "http://longurl.org/services",
            ["ta.gd"] = "http://urlshortener.org",
            ["tak.bz"] = "http://urlshortener.org",
            ["takeme.to"] = "http://urlshortener.org",
            ["tbd.ly"] = "http://longurl.org/services",
            ["tcrn.ch"] = "http://longurl.org/services",
            ["te.tl"] = "http://urlshortener.org",
            ["tgr.me"] = "http://longurl.org/services",
            ["tgr.ph"] = "http://longurl.org/services",
            ["thecow.me"] = "http://urlshortener.org",
            ["tighturl.com"] = "http://urlshortener.org",
            ["tiniuri.com"] = "http://longurl.org/services",
            ["tiny.cc"] = "http://urlshortener.org",
            ["tiny.ly"] = "http://longurl.org/services",
            ["tiny.pl"] = "http://urlshortener.org",
            ["tiny.tw"] = "N/A",
            ["tiny2go.com"] = "http://urlshortener.org",
            ["tinyftw.com"] = "http://urlshortener.org",
            ["tinylink.in"] = "http://longurl.org/services",
            ["tinyuri.ca"] = "http://longurl.org/services",
            ["tinyurl.com"] = "http://urlshortener.org",
            ["tl.gd"] = "http://longurl.org/services",
            ["tmi.me"] = "http://longurl.org/services",
            ["tnij.org"] = "http://longurl.org/services",
            ["tnw.to"] = "http://longurl.org/services",
            ["tny.com"] = "http://longurl.org/services",
            ["to.ly"] = "http://longurl.org/services",
            ["togoto.us"] = "http://longurl.org/services",
            ["totc.us"] = "http://longurl.org/services",
            ["toysr.us"] = "http://longurl.org/services",
            ["tpm.ly"] = "http://longurl.org/services",
            ["tr.im"] = "http://longurl.org/services",
            ["tra.kz"] = "http://urlshortener.org",
            ["trunc.it"] = "http://urlshortener.org",
            ["tuaurl.com"] = "http://urlshortener.org",
            ["turls.me"] = "http://urlshortener.org",
            ["tutz.me"] = "http://urlshortener.org",
            ["tw3.it"] = "http://urlshortener.org",
            ["tweak.tk"] = "http://urlshortener.org",
            ["tweez.me"] = "http://urlshortener.org",
            ["twhub.com"] = "http://longurl.org/services",
            ["twi.tl"] = "http://urlshortener.org",
            ["twirl.at"] = "http://longurl.org/services",
            ["twitclicks.com"] = "http://longurl.org/services",
            ["twitterto.com"] = "http://urlshortener.org",
            ["twitterurl.net"] = "http://urlshortener.org",
            ["twitterurl.org"] = "http://longurl.org/services",
            ["twiturl.de"] = "http://urlshortener.org",
            ["twurl.cc"] = "http://longurl.org/services",
            ["twurl.nl"] = "http://urlshortener.org",
            ["u.go2.me"] = "http://urlshortener.org",
            ["u.mavrev.com"] = "http://longurl.org/services",
            ["u.nu"] = "http://longurl.org/services",
            ["u76.org"] = "http://longurl.org/services",
            ["ub0.cc"] = "http://longurl.org/services",
            ["ulu.lu"] = "http://longurl.org/services",
            ["updating.me"] = "http://longurl.org/services",
            ["ur1.ca"] = "http://longurl.org/services",
            ["url.az"] = "http://longurl.org/services",
            ["url.co.uk"] = "http://longurl.org/services",
            ["url.ie"] = "http://urlshortener.org",
            ["url.in.it"] = "N/A",
            ["url.to.it"] = "http://urlshortener.org",
            ["url360.me"] = "http://longurl.org/services",
            ["url4.eu"] = "http://longurl.org/services",
            ["urlbit.us"] = "http://urlshortener.org",
            ["urlborg.com"] = "http://longurl.org/services",
            ["urlbrief.com"] = "http://longurl.org/services",
            ["urlcover.com"] = "http://urlshortener.org",
            ["urlcut.com"] = "http://longurl.org/services",
            ["urlenco.de"] = "http://longurl.org/services",
            ["urli.nl"] = "http://longurl.org/services",
            ["urlit.net"] = "http://urlshortener.org",
            ["urlminifier.com"] = "http://urlshortener.org",
            ["urlmorph.com"] = "http://urlshortener.org",
            ["urlpire.com"] = "http://urlshortener.org",
            ["urls.im"] = "http://longurl.org/services",
            ["urlx.ie"] = "http://longurl.org/services",
            ["urlxp.com"] = "http://urlshortener.org",
            ["urlzen.com"] = "http://longurl.org/services",
            ["usat.ly"] = "http://longurl.org/services",
            ["use.my"] = "http://longurl.org/services",
            ["ushort.co.uk"] = "http://urlshortener.org",
            ["ux.lv"] = "http://urlshortener.org",
            ["vani.sh"] = "http://urlshortener.org",
            ["vb.ly"] = "http://longurl.org/services",
            ["vgn.am"] = "http://longurl.org/services",
            ["viewista.com"] = "http://urlshortener.org",
            ["virl.com"] = "http://urlshortener.org",
            ["vl.am"] = "http://longurl.org/services",
            ["vm.lc"] = "http://longurl.org/services",
            ["vs0.net"] = "N/A",
            ["w0p.de"] = "http://urlshortener.org",
            ["w55.de"] = "http://longurl.org/services",
            ["wapo.st"] = "http://longurl.org/services",
            ["wapurl.co.uk"] = "http://longurl.org/services",
            ["webalias.com"] = "http://urlshortener.org",
            ["weshort.in"] = "http://urlshortener.org",
            ["whit.me"] = "http://urlshortener.org",
            ["widg.me"] = "N/A",
            ["wipi.es"] = "http://longurl.org/services",
            ["wp.me"] = "http://longurl.org/services",
            ["wurl.ca"] = "http://urlshortener.org",
            ["wurl.ws"] = "http://urlshortener.org",
            ["wva.gd"] = "http://urlshortener.org",
            ["wwb.in"] = "http://urlshortener.org",
            ["x.co"] = "http://app.x.co/",
            ["x.se"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["x.vu"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["x2t.com"] = "http://urlshortener.org",
            ["xa.ly"] = "http://xa.ly/",
            ["xaddr.com"] = "http://urlshortener.org",
            ["xiy.net"] = "http://urlshortener.org",
            ["xpnd.it"] = "http://long-shore.com/expand",
            ["xr.com"] = "http://urlshortener.org",
            ["xrl.in"] = "http://longurl.org/services",
            ["xrl.us"] = "http://longurl.org/services",
            ["xurl.es"] = "http://longurl.org/services",
            ["xurl.jp"] = "http://urlshortener.org",
            ["y.ahoo.it"] = "http://longurl.org/services",
            ["yatuc.com"] = "http://longurl.org/services",
            ["ye.pe"] = "http://longurl.org/services",
            ["yep.it"] = "http://urlshortener.org",
            ["yfrog.com"] = "http://longurl.org/services",
            ["yhoo.it"] = "http://longurl.org/services",
            ["yi.pe"] = "N/A",
            ["yiyd.com"] = "http://longurl.org/services",
            ["youtu.be"] = "http://longurl.org/services",
            ["yuarel.com"] = "http://longurl.org/services",
            ["yvy.me"] = "http://yvy.me/",
            ["z.pe"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["z0p.de"] = "http://longurl.org/services",
            ["zapit.nu"] = "http://urlshortener.org",
            ["zeek.us"] = "http://urlshortener.org",
            ["zi.ma"] = "http://longurl.org/services",
            ["zi.mu"] = "http://longurl.org/services",
            ["zipmyurl.com"] = "http://longurl.org/services",
            ["ziprl.com"] = "http://urlshortener.org",
            ["zkracene.cz"] = "http://zkracene.cz/",
            ["zolp.net"] = "N/A",
            ["zud.me"] = "http://longurl.org/services",
            ["zurl.ws"] = "http://urlshortener.org",
            ["zwap.to"] = "http://urlshortener.org",
            ["zxc9.com"] = "http://urlshortener.org",
            ["zz.gd"] = "http://longurl.org/services",
            ["zzang.kr"] = "http://longurl.org/services",
            ["zzz.ee"] = "http://urlshortener.org",
            ["joturl.com"] = "http://www.joturl.comS",
            ["co.nr"] = "http://www.freedomain.co.nr/",
        }.ToImmutableDictionary();
        
        public static readonly Regex UrlShortenerRegex = LinkRemoverConstants.CreateLiteralRegex(UrlShorteners.Keys.ToArray());
    }
}