using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using DSharpPlus;
using DSharpPlus.Entities;
using DSharpPlus.EventArgs;
using ModCore.Database;
using ModCore.Database.JsonEntities;
using ModCore.Entities;
using ModCore.Extensions.AsyncListeners.Attributes;
using ModCore.Extensions.AsyncListeners.Enums;
using ModCore.Logic;
using ModCore.Logic.Extensions;

namespace ModCore.Listeners
{
    public static class Linkfilter
    {
        public static Regex InviteRegex { get; } =
            new Regex(@"discord(?:\.gg|app\.com\/invite)\/([\w\-]+)", RegexOptions.Compiled);

        public static ConcurrentDictionary<string, DiscordInvite> InviteCache { get; } =
            new ConcurrentDictionary<string, DiscordInvite>();

        [AsyncListener(EventType.MessageCreated)]
        public static async Task RemoveSuspiciousLinks(MessageCreateEventArgs eventargs, DatabaseContextBuilder database, DiscordClient client)
        {
            if (eventargs.Author == null || eventargs.Channel == null)
                return;

            if (eventargs.Message.WebhookMessage)
                return;

            if ((eventargs.Channel.PermissionsFor(eventargs.Author as DiscordMember) & Permissions.ManageMessages) != 0) return;

            if (eventargs.Channel.Guild == null)
                return;

            GuildSettings config;
            using (var db = database.CreateContext())
                config = eventargs.Guild.GetGuildSettings(db);
            if (config == null)
                return;

            var lfSettings = config.Linkfilter;
            if (!lfSettings.Enable)
                return;

            if (lfSettings.ExemptUserIds.Contains(eventargs.Message.Author.Id))
                return;

            if (eventargs.Message.Author is DiscordMember member &&
                member.Roles.Select(xr => xr.Id).Intersect(lfSettings.ExemptRoleIds).Any())
                return;

            if (lfSettings.BlockInviteLinks)
                await FindAndPurgeInvites(client, eventargs, lfSettings);

            if (lfSettings.BlockIpLoggers)
            {
                var match = LinkRemoverMatchers.IpLogger.Check(eventargs.Message);
                if (match.Success)
                {
                    await eventargs.Message.DeleteAsync($"Discovered IP logger site <{match.Matched}> and deleted message");
                    await (eventargs.Author as DiscordMember).ElevatedMessageAsync(
                        $"Your message ```\n{eventargs.Message.Content}``` was automatically removed from " +
                        $"{eventargs.Guild.Name}#{eventargs.Channel.Name} because it contained a link to an IP logger website: **`{match.Matched}`**");
                }
            }

            if (lfSettings.BlockBooters)
            {
                var match = LinkRemoverMatchers.BooterRegex.Check(eventargs.Message);
                if (match.Success)
                {
                    await eventargs.Message.DeleteAsync($"Discovered Booter/DDoS site <{match.Matched}> and deleted message");
                    await (eventargs.Author as DiscordMember).ElevatedMessageAsync(
                        $"Your message ```\n{eventargs.Message.Content}``` was automatically removed from " +
                        $"{eventargs.Guild.Name}#{eventargs.Channel.Name} because it contained a link to a DDoS/booter website: **`{match.Matched}`**");
                }
            }

            if (lfSettings.BlockShockSites)
            {
                var match = LinkRemoverMatchers.ShockSiteRegex.Check(eventargs.Message);
                if (match.Success)
                {
                    await eventargs.Message.DeleteAsync($"Discovered shock site <{match.Matched}> and deleted message");
                    await (eventargs.Author as DiscordMember).ElevatedMessageAsync(
                        $"Your message ```\n{eventargs.Message.Content}``` was automatically removed from " +
                        $"{eventargs.Guild.Name}#{eventargs.Channel.Name} because it contained a link to a shock/gore site: **`{match.Matched}`**");
                }
            }

            // separate method to avoid loading the url shortener class (and all the strings inside) if not necessary.
            // this saves a lot of memory if you don't care about URL shorteners.
            if (lfSettings.BlockUrlShorteners)
                await MatchUrlShorteners(eventargs);
        }

        private static async Task FindAndPurgeInvites(DiscordClient client, MessageCreateEventArgs eventargs,
            GuildLinkfilterSettings linkfilter)
        {
            var matches = InviteRegex.Matches(eventargs.Message.Content);
            if (!matches.Any())
                return;

            foreach (Match match in matches)
            {
                var invk = match.Groups[1].Value;
                if (!InviteCache.TryGetValue(invk, out var inv))
                {
                    inv = await client.GetInviteByCodeAsync(invk);
                    InviteCache.TryAdd(invk, inv);
                }

                if (linkfilter.ExemptInviteGuildIds.Contains(inv.Guild.Id))
                    continue;

                await eventargs.Message.DeleteAsync($"Discovered invite <{inv.Code}> and deleted message");
                break;
            }
        }

        private static async Task MatchUrlShorteners(MessageCreateEventArgs eventargs)
        {
            var match = UrlShortenerConstants.UrlShortenerRegex.Check(eventargs.Message);
            if (match.Success)
            {
                var origin = UrlShortenerConstants.UrlShorteners[match.Matched];
                await eventargs.Message.DeleteAsync(
                    $"Discovered URL shortener <{match.Matched}> and deleted message. Info: <{origin}>");
                await (eventargs.Author as DiscordMember).ElevatedMessageAsync(
                    $"Your message ```\n{eventargs.Message.Content}``` was automatically removed from " +
                    $"{eventargs.Guild.Name}#{eventargs.Channel.Name} because it contained a link to an URL shortener: **`{match.Matched}`**\n" +
                    $"This URL shortener seems to have originated from the following domain: **`{origin}`**");
            }
        }
    }

    // TODO: can move this to JSON.

    public static class LinkRemoverMatchers
    {
        /// <summary>
        /// Regex to match IP logger sites.
        /// </summary>
        public static readonly LinkfilterMatcher IpLogger =
            new LinkfilterMatcher(
                "iplogger.org",
                "2no.co",
                "ezstat.ru",
                "iplogger.info",
                "02ip.ru",
                "iplo.ru",
                "iplis.ru",
                "iplogger.com",
                "iplogger.ru",
                "iplogger.org",
                "pgrabber.ru",
                "grabify.link",
                "ip.jlynx.net",
                "deviantartt.ml",
                "dropboxx.lm ",
                "gyazoo.ga",
                "linkit.cf",
                "printscr.ga",
                "youutube.gq",
                "strawpoll.ga",
                "xxox.co.uk",
                "leakforum.ga",
                "prntsc.cf",
                "deviantartt.ga",
                "dropboxx.ga",
                "dropboxx.cf",
                "strawpolll.ga",
                "twitte.ga",
                "bvog.com",
                "hondachat.com",
                "youramonkey.com",
                "blasze.tk",
                "myiptest.com/img.php",
                "ip-grabber.com",
                "imgurl.us",
                "skypegrab.net",
                "sciencefuture.tk",
                "stresser.science",
                "imageshack.ml",
                "viphackforums.xyz",
                "gtadb.net",
                "fotocerdas.com",
                "parlament.usa.cc",
                "hs.vc",
                "community.hackersclub.net",
                "login.anal-porn.info",
                "paypal.sellbitcoins.com",
                "panel.teamspeak.bz	",
                "files.uploads.ws",
                "cubeupload.com",
                "media.appspot.com",
                "hackfȯrums.net",
                "hackfȯrums.com",
                "imgúr.com",
                "battlė.net",
                "dank.host",
                "r1p.pw",
                "webprofile.me",
                "anonymousforum.pw",
                "ts3free.top",
                "viphackforum.xyz",
                "bbcnews.today",
                "privatexmpp.me",
                "topstreaming.us",
                "topcdn.biz",
                "postimage.co",
                "hackernews.online",
                "hdblog.tech",
                "sexy18.webcam",
                "dropbox.desi",
                "hostingonline.desi",
                "freeanonymous.host",
                "ampnode.host",
                "spoofing.host",
                "cubeupload.xyz",
                "exploit-db.xyz",
                "gyazoo.xyz",
                "ipddoser.xyz",
                "skypecracker.xyz",
                "ipsnatcher.com",
                "skidpaste.org",
                "cloudfsx.com",
                "ps3cfw.com",
                // third party
                "aruljohn.com/widget/zip/",
                "aruljohn.com/widget/ip/");

        /// <summary>
        /// Regex to match booter/DDoS as a Service sites.
        /// </summary>
        public static readonly LinkfilterMatcher BooterRegex =
            new LinkfilterMatcher(
                "orcahub.com",
                "vbooter.org",
                "orboot.pw",
                "ddos.city",
                "restresser.com",
                "networkstresser.com",
                "vdos-s.com",
                "oxystress.eu",
                "freebooter.pro",
                "bootyou.net",
                "critical-boot.com");

        public static readonly LinkfilterMatcher ShockSiteRegex =
            new LinkfilterMatcher(
                "happypuppies.net",
                "meatspin.fr",
                "jarsquatter.com",
                "goatse.ru",
                "goatse.info",
                "rightxd.org",
                "agor.io",
                "anne.jpg",
                "findminecraft.com",
                "shafou.com",
                "strawpoii",
                "strawpoii.me",
                "herobrine.com",
                "x-rider.com",
                "420yolo.com",
                "jultavling.se",
                "killwithus.com",
                "fearnest.ru",
                "minecraft.swf",
                "pumba.swf",
                "sscary.ru",
                "zerotec.comxa.com",
                "zerotec.net16.net",
                "bestshockers.com/1-guy-1-screwdriver",
                "ogrish.tv/play.php?vid=148",
                "shockchan.com/1-man-1-screwdriver",
                "netbroadcaster.com/new/shorts/flash/viewswf.cgi",
                "albinoblacksheep.com/flash/kikia.php",
                "fetchfido.co.uk/games/kikia/kikia.htm",
                "albinoblacksheep.com/flash/subliminal",
                "killsometime.com/animations/animation.asp?id=119",
                "monkeydoo.com/onlineflash_remotescan.php",
                "sugarqube.com/ecards/cardview.cfm?cardid=1371&l1=186&l2=253&l3=0&page=",
                "sugarqube.com/ecards/cardview.cfm?cardid=1228",
                "sugarqube.com/ecards/cardview.cfm?cardid=1120&l1=1&l2=66&l3=0&page=",
                "jkcinema.com",
                "martectx.de/whatswrong.swf",
                "liquidgeneration.com/trick-or-treat",
                "putfile.com/2-ringed-ufo",
                "newgrounds.com/portal/view/464999",
                "sinthaistudio.com/alrena",
                "members.multimania.co.uk/martyncruise/scream.html",
                "watch?v=kybc1rzjyye",
                "watch?v=iigda5q9egq",
                "img101.imageshack.us/my.php?image=dancincats5ze.swf",
                "watch?v=nvldwxi3wds",
                "watch?v=yts5zz-ooum",
                "dragonsplace.co.uk/flash/colourblind.html",
                "liquidgeneration.com/content/a55hat.aspx?cid=709",
                "thatguywiththeglasses.com/videolinks/thatguywiththeglasses/ask-thatguy/505-ask-thatguy-episode-5",
                "liquidgeneration.com/content/a55hat.aspx?cid=1215",
                "watch?v=nx0ugvkabsq",
                "media.putfile.com/bnfjg",
                "watch?v=l2c_movv1v8",
                "geocities.com/patlee_69",
                "img342.imageshack.us/my.php?image=beach7fa.swf",
                "watch?v=ec89gxfltt8",
                "watch?v=4xjhorxrqiw",
                "watch?v=yzccz0sosz4",
                "watch?v=nqoecxkxhcs",
                "watch?v=oiiaa3ul9pu",
                "watch?v=qco6noighgi",
                "liquidgeneration.com/content/a55hat.aspx?cid=1620",
                "brainpop.com/socialstudies/culture/halloween",
                "watch?v=vpfygvordhi",
                "watch?v=jnn_uolut_i",
                "media.putfile.com/britney-spears-hidden-message",
                "winterrowd.com/bubblewrap",
                "watch?v=oqfcxths8re",
                "watch?v=qiihriphk4y",
                "watch?v=dtvodaquj3m",
                "watch?v=z21f6dfamji",
                "watch?v=k86685loths",
                "newgrounds.com/portal/view/301773",
                "albinoblacksheep.com/flash/halloween.php",
                "albinoblacksheep.com/flash/chris2.php",
                "albinoblacksheep.com/flash/chris3.php",
                "newgrounds.com/portal/view/475574",
                "newgrounds.com/portal/view/47612",
                "newgrounds.com/portal/view/43663",
                "computerpranks.com/download/online-fun/color.swf",
                "ebaumsworld.com/2006/03/lightning.html",
                "watch?v=qv6wluc9duc&feature=channel",
                "dragonsplace.co.uk/flash/sheep.html",
                "watch?v=6o5j0pcrvje",
                "icarly.com/ivideo/index.html#vid4602",
                "watch?v=4eqz2rdahfg&feature=channel",
                "watch?v=aasawjdrjfq",
                "watch?v=fp2u9nowxoy",
                "liquidgeneration.com/content/a55hat.aspx?cid=567",
                "watch?v=zyc3c1kb0tg",
                "watch?v=6cp1h0fuig4",
                "watch?v=chqjrupkv9u",
                "online.sector.sk/hra.aspx?game=1368",
                "liquidgeneration.com/content/showmedacontent.aspx?cid=2020",
                "watch?v=j1q-czzakq0",
                "liquidgeneration.com/media/sabotage/divine_visions_of_mary__jesus",
                "winterrowd.com/maze",
                "collegegags.com/index.php/collegegags/displaycontent/scare_prank",
                "watch?v=dtg1qy4q7mw",
                "liquidgeneration.com/content/a55hat.aspx?cid=1177",
                "podrido.com/melodias",
                "kontraband.com/show/show.asp?id=2320&cat=games&nsfw=0&rtn=search-2320&keywords=spooky%20ro",
                "monkeydoo.com/view/pranks/3/expert:_mouse_racing.html",
                "liquidgeneration.com/content/showmedacontent.aspx?cid=2222",
                "winterrowd.com/exorcist",
                "albinoblacksheep.com/flash/sajjad.php",
                "watch?v=kb1mjgy8xic",
                "img489.imageshack.us/my.php?image=sadness3kr.swf",
                "watch?v=39d3lebowbs",
                "avatarmagic.com/fingertwister/game.php",
                "liquidgeneration.com/media/animations/weird_random/sick_twisted/fire_safety_with_ready_fre",
                "watch?v=8w2pbnk3tka",
                "watch?v=roprqyrbxkq",
                "optillusions.com/dp/1-51.htm",
                "haunted.org/html/fright_gauge.html",
                "go.interwebline.de/shock/o_13.php",
                "watch?v=5ir8pwydzo4",
                "home22.inet.tele.dk/flash/swf/gamemun.swf",
                "ghostboy.co.uk/ghostboywho.htm",
                "armorgames.com/play/2521/ghostscape",
                "watch?v=5hwqnssvaoa",
                "watch?v=buxonoenm8a",
                "media.putfile.com/ghost-footage",
                "watch?v=wijf3xgq4ng",
                "albinoblacksheep.com/flash/handeye.php",
                "liquidgeneration.com/media/sabotage/halloween_safety_tips_with_jack_o_lantern",
                "alienatedmedia.com/xperiments/happyhalloween",
                "watch?v=ei0fn6ijd0o",
                "liquidgeneration.com/media/pranks/fake_tests/all_fake_tests/are_you_going_to_heaven_or_hell",
                "watch?v=nv86johtzc4",
                "watch?v=hmu2ydip0bo",
                "video.google.com/videoplay?docid=-6344215419730491458&q=lost&pl=true",
                "watch?v=1t9bgxqgths",
                "winterrowd.com/hitthedot",
                "subliminalmessages.com/vip%20subliminal%2061a.htm",
                "albinoblacksheep.com/flash/vision.php",
                "freeonlinegames.com/play/1560.html",
                "newgrounds.com/portal/view/279778",
                "watch?v=t49v2r5pg-0",
                "watch?v=rdrcxbl37pq",
                "liquidgeneration.com/content/a55hat.aspx?cid=1131",
                "liquidgeneration.com/content/a55hat.aspx?cid=1707",
                "liquidgeneration.com/how-to-cook-the-perfect-hamburger",
                "liquidgeneration.com/content/a55hat.aspx?cid=1483",
                "winterrowd.com/hindu_life_tips",
                "rabailkal.com/hypnose.htm",
                "absolu-flash.com/horror-games/index.php?rubrique=peur",
                "watch?v=yqzidpx0p-c",
                "watch?v=hwbjyihpuvi",
                "liquidgeneration.com/media/pranks/holiday/all_holiday/the_illusion_of_bloody_mary",
                "liquidgeneration.com/content/a55hat.aspx?cid=950",
                "watch?v=jgxsdkakkke",
                "albinoblacksheep.com/flash/inkblot.php",
                "watch?v=auq3hmqwfrc",
                "watch?v=zzkcrafz6gq",
                "ebaumsworld.com/albanude.html",
                "alienredwolf.com",
                "watch?v=pmqnqcmktss",
                "subliminalmessages.com/p999.htm",
                "k-fee.com",
                "watch?v=6-xtf3w1opk",
                "watch?v=nbf4vv-clfq&feature=relmfu",
                "liquidgeneration.com/content/a55hat.aspx?cid=241",
                "liquidgeneration.com/content/a55hat.aspx?cid=228",
                "filecabi.net/video/london-ghost.html",
                "media.tumblr.com/tumblr_lft3yaxwva1qddxbt.gif",
                "gorekiller.newgrounds.com",
                "liquidgeneration.com/content/a55hat.aspx?cid=311",
                "newgrounds.com/portal/view/294974",
                "freewebs.com/jesposworld/weirdspidermancomic.htm",
                "watch?v=lpccgflnw24",
                "watch?v=6zu9svx2l7a&feature=related",
                "www.cadred.org/media/images/image/36016",
                "members.lycos.co.uk/martyncruise/scare.html",
                "watch?v=yfyiheu-tvg",
                "winterrowd.com/lostdog",
                "watch?v=-zh6e1fwq7o&feature=related",
                "watch?v=7cjrmuljakc",
                "watch?v=q5mriedpcz0",
                "watch?v=epnwv3giwlg&feature=related",
                "watch?v=vzikgcqc0us",
                "newgrounds.com/portal/view/311234",
                "watch?v=vdk_puyvt4c",
                "watch?v=drep8080mz8",
                "liquidgeneration.com/media/pranks/fake_tests/all_fake_tests/online_fitness_check",
                "liquidgeneration.com/content/a55hat.aspx?cid=922",
                "liquidgeneration.com/content/a55hat.aspx?cid=1183",
                "liquidgeneration.com/media/videos/viral_videos/bizarre/optical_illusion_ames_window",
                "liquidgeneration.com/content/a55hat.aspx?cid=236",
                "liquidgeneration.com/content/a55hat.aspx?cid=341",
                "winterrowd.com/peeping-tom",
                "vision.badgerville.org",
                "winterrowd.com/jeremy",
                "watch?v=1sexyy9pocs",
                "nobodyhere.com/justme/present.here",
                "watch?v=c-de18t8efo",
                "watch?v=afk9x2iuuyc",
                "liquidgeneration.com/content/a55hat.aspx?cid=897",
                "watch?v=j3wk9ihetya&feature=related",
                "web.archive.org/web/20081011044436/http://img165.imageshack.us/my.php?image=robluccithegame3gi.swf",
                "liquidgeneration.com/media/pranks/weird_random/all_weird_random/satanic_messages_in_music",
                "watch?v=0ys2zguu5gg",
                "albinoblacksheep.com/flash/sayit.php",
                "subliminalmessages.com/p7b.htm",
                "funnyjunk.com/pages/watch.htm",
                "monkeydoo.com/cool8.php?i=11131",
                "watch?v=5wrsqt9f738",
                "watch?v=wy0c6vpr8_g&feature=related",
                "watch?v=8d2pxc1tsvq",
                "liquidgeneration.com/content/a55hat.aspx?cid=1329",
                "media.putfile.com/sexy-ice-cream-message",
                "liquidgeneration.com/content/a55hat.aspx?cid=1515",
                "watch?v=pwkwzqdog0i",
                "shinysearch.com/prank/fakegoogle.php?mode=demo",
                "winterrowd.com/simon",
                "liquidgeneration.com/content/a55hat.aspx?cid=828",
                "watch?v=8xo2x_62fqq",
                "liquidgeneration.com/content/showmedacontent.aspx?cid=2307",
                "watch?v=wa4x_cvb-la&feature=related",
                "watch?v=ruipj0kpgzi&feature=related",
                "watch?v=6tbzyqn-62k",
                "liquidgeneration.com/content/a55hat.aspx?cid=1591",
                "starterupsteve.com/swf/steadyhand.html",
                "watch?v=lund56xag4g",
                "watch?v=wz0o0lukhig",
                "watch?v=nt1tuuy_qq4",
                "liquidgeneration.com/content/a55hat.aspx?cid=1956",
                "winterrowd.com/supermariobros",
                "winterrowd.com/swearing-baby",
                "weebls-stuff.com/toons/taken",
                "watch?v=vfk74svzrzk",
                "testyoursenses.com",
                "newgrounds.com/portal/view/234890",
                "watch?v=yo-viwpdgtq",
                "liquidgeneration.com/content/showmedacontent.aspx?cid=2268",
                "ethereality.info/ethereality_website/paintings_drawings/new/illustrations/melancholic_princess/melancholic_princess.htm",
                "watch?v=kq3ixm3tg7q",
                "winterrowd.com/ultimatemaze",
                "watch?v=x0p32-y-q9g",
                "alienredwolf.com/watch/thisisneville.html",
                "pyzam.com/tictactoe",
                "video.google.com/videoplay?docid=-781295686117548807&hl=en",
                "video.google.com/videoplay?docid=5400390924456577745&hl=en",
                "watch?v=dsuz3og9kl0&feature=related",
                "watch?v=wy88nnkid18",
                "media.putfile.com/tour-of-the-universe",
                "watch?v=pl_eblg45ew",
                "watch?v=ll03dliyv9c",
                "liquidgeneration.com/content/a55hat.aspx?cid=1103",
                "funnyjunk.com/pages/image.htm",
                "watch?v=pi3g_8_3_kk",
                "liquidgeneration.com/content/a55hat.aspx?cid=1883",
                "video.google.ca/videoplay?docid=-1552180646875208863&ei=30kgsuxre6bmqql7jbwxbw&hl=en",
                "watch?v=se8sgjla9ha",
                "liquidgeneration.com/media/videos/lg_originals/other_lg_originals/watch_out_for_strangers",
                "watch?v=kpade6txi_q",
                "smartmindmedia.com/flash/play.php?id=camera&width=400&height=350",
                "watch?v=qmpypcpiswc",
                "watch?v=ehtujuxj9ai&feature=channel",
                "funny-spot.com/html/whats-wrong-with-this-picture.html",
                "funshack.com/scary.html",
                "liquidgeneration.com/content/a55hat.aspx?cid=506",
                "albinoblacksheep.com/flash/waldo.php",
                "superlaugh.com/1/waldo.htm",
                "liquidgeneration.com/content/a55hat.aspx?cid=671",
                "winterrowd.com/illusions.htm",
                "watch?v=adlny0ciw4a",
                "scaryforkids.com/pics/yahoo-search.htm",
                "yenimports.co.uk",
                "members.home.nl/saen/special/zoeken.swf",
                "www.newgrounds.com/portal/view/452252",
                "killwithme.com",
                "spankwire.com",
                "playerreview.net",
                "fbcdn-sphotos-g-a.cloudliv.net/hphotos-ak-ash4/2836620_371023452991370_441600357_n.jpg",
                "akk.li",
                "whoomp.org",
                "weticecream.com",
                "specialfriedrice.net",
                "bluewaffle.net",
                "ballsack.org",
                "discharges.org",
                "ogrish.com",
                "rotten.com",
                "bestgore.com",
                "lemonparty.org",
                "hai2u.com",
                "goatse.fr",
                "2girls1cup.com",
                "tubgirl.ca",
                "meatspin.com");
    }

    public class LinkfilterMatch
    {
        public bool Success { get; }
        public string Matched { get; }
        
        public LinkfilterMatch(Match match)
        {
            this.Success = match.Success;
            this.Matched = match.Groups[0].Value;
        }
    }

    public class LinkfilterMatcher : Regex
    {
        public LinkfilterMatcher(params string[] items) : base($@"({string.Join('|', items.Select(Escape))})")
        {
        }
        
        public LinkfilterMatcher(IEnumerable<string> items) : base($@"({string.Join('|', items.Select(Escape))})")
        {
        }

        public LinkfilterMatch Check(DiscordMessage message)
        {
            return new LinkfilterMatch(Match(message.Content));
        }
    }

    // use a separate class to avoid class loader bloat
    public static class UrlShortenerConstants
    {
        public static readonly ImmutableDictionary<string, string> UrlShorteners = new Dictionary<string, string>
        {
            ["jesais.fr"] = "http://www.jelev.eu/accueil.php",
            ["aelita.fr"] = "http://www.jelev.eu/accueil.php",
            ["jelev.eu"] = "http://www.jelev.eu/accueil.php",
            ["jesais.fr"] = "http://www.jelev.eu/accueil.php",
            ["jtefaisla.biz"] = "http://www.jelev.eu/accueil.php",
            ["lacheun.com"] = "http://www.jelev.eu/accueil.php",
            ["lyoko.eu"] = "http://www.jelev.eu/accueil.php",
            ["mattemon.info"] = "http://www.jelev.eu/accueil.php",
            ["monbe.be"] = "http://www.jelev.eu/accueil.php",
            ["oueb.eu"] = "http://www.jelev.eu/accueil.php",
            ["pourle.net"] = "http://www.jelev.eu/accueil.php",
            ["xana.fr"] = "http://www.jelev.eu/accueil.php",
            ["smll.me"] = "http://smll.me",
            ["06.hk"] = "http://urlshortener.org",
            ["kwik.to"] = "http://sitelutions.com",
            ["0rz.tw"] = "http://0rz.tw",
            ["10.rs"] = "http://urlshortener.org",
            ["1iny.com"] = "http://urlshortener.org",
            ["1kh.de"] = "http://urlshortener.org",
            ["1link.in"] = "http://longurl.org/services",
            ["1tja.com"] = "N/A",
            ["1url.com"] = "http://www.mrbup.com",
            ["2.gp"] = "http://longurl.org/services",
            ["2big.at"] = "http://urlshortener.org",
            ["2tr.net"] = "http://urlshortener.org",
            ["2tu.us"] = "http://urlshortener.org",
            ["3.ly"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["307.to"] = "http://longurl.org/services",
            ["4ms.me"] = "http://longurl.org/services",
            ["4nu.net"] = "N/A",
            ["4sq.com"] = "http://longurl.org/services",
            ["4url.cc"] = "http://longurl.org/services",
            ["55c.cc"] = "http://urlshortener.org",
            ["6t4.us"] = "http://urlshortener.org",
            ["6url.com"] = "http://longurl.org/services",
            ["7.ly"] = "http://longurl.org/services",
            ["7les.com"] = "http://urlshortener.org",
            ["98.to"] = "http://98.to/tc/home.asp",
            ["a.gg"] = "http://longurl.org/services",
            ["a.nf"] = "http://longurl.org/services",
            ["a.nf"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["aa.cx"] = "http://longurl.org/services",
            ["abcurl.net"] = "http://longurl.org/services",
            ["abe5.com"] = "http://urlshortener.org",
            ["ad.vu"] = "http://longurl.org/services",
            ["adf.ly"] = "http://longurl.org/services",
            ["adjix.com"] = "http://longurl.org/services",
            ["afx.cc"] = "http://longurl.org/services",
            ["all.fuseurl.com"] = "http://longurl.org/services",
            ["alturl.com"] = "http://longurl.org/services",
            ["amzn.to"] = "http://longurl.org/services",
            ["ao.co.za"] = "http://urlshortener.org",
            ["apu.sh"] = "http://urlshortener.org",
            ["ar.gy"] = "http://longurl.org/services",
            ["arm.in"] = "http://urlshortener.org",
            ["arst.ch"] = "http://longurl.org/services",
            ["atu.ca"] = "http://longurl.org/services",
            ["ax.ag"] = "http://urlshortener.org",
            ["azc.cc"] = "http://longurl.org/services",
            ["b00b.tk"] = "http://urlshortener.org",
            ["b23.ru"] = "http://longurl.org/services",
            ["b2l.me"] = "http://urlshortener.org",
            ["bacn.me"] = "http://longurl.org/services",
            ["bcool.bz"] = "http://longurl.org/services",
            ["biglnk.com"] = "http://urlshortener.org",
            ["binged.it"] = "http://longurl.org/services",
            ["bit.ly"] = "http://longurl.org/services",
            ["bizj.us"] = "http://longurl.org/services",
            ["bizy.be"] = "http://urlshortener.org",
            ["bizz.cc"] = "http://urlshortener.org",
            ["bloat.me"] = "http://longurl.org/services",
            ["bpt.st"] = "http://urlshortener.org",
            ["br.st"] = "http://urlshortener.org",
            ["bravo.ly"] = "http://longurl.org/services",
            ["bsa.ly"] = "http://longurl.org/services",
            ["budurl.com"] = "http://longurl.org/services",
            ["canurl.com"] = "http://urlshortener.org",
            ["cd4.me"] = "http://urlshortener.org",
            ["checkthislink.com"] = "http://urlshortener.org",
            ["chilp.it"] = "http://longurl.org/services",
            ["chrst.ph"] = "http://urlshortener.org",
            ["chs.mx"] = "http://urlshortener.org",
            ["chzb.gr"] = "http://longurl.org/services",
            ["cl.lk"] = "http://longurl.org/services",
            ["clck.ru"] = "http://urlshortener.org",
            ["cli.gs"] = "http://urlshortener.org",
            ["cliccami.info"] = "http://longurl.org/services",
            ["clickthru.ca"] = "http://longurl.org/services",
            ["clockurl.com"] = "http://urlshortener.org",
            ["clop.in"] = "http://urlshortener.org",
            ["coge.la"] = "N/A",
            ["conta.cc"] = "http://longurl.org/services",
            ["cort.as"] = "http://urlshortener.org",
            ["cot.ag"] = "http://longurl.org/services",
            ["cr.am"] = "http://urlshortener.org",
            ["crks.me"] = "http://longurl.org/services",
            ["cru.ms"] = "http://urlshortener.org",
            ["ctvr.us"] = "http://longurl.org/services",
            ["cut.by"] = "http://urlshortener.org",
            ["cutt.us"] = "http://longurl.org/services",
            ["d3c.co"] = "N/A",
            ["dai.ly"] = "http://longurl.org/services",
            ["decenturl.com"] = "http://longurl.org/services",
            ["delivr.com"] = "http://urlshortener.org",
            ["devnull.at"] = "http://urlshortener.org",
            ["df9.net"] = "http://urlshortener.org",
            ["dfl8.me"] = "http://urlshortener.org",
            ["dickensurl.com"] = "http://urlshortener.org",
            ["digbig.com"] = "http://longurl.org/services",
            ["digg.com"] = "http://longurl.org/services",
            ["disq.us"] = "http://longurl.org/services",
            ["dld.bz"] = "http://longurl.org/services",
            ["dlvr.it"] = "http://longurl.org/services",
            ["do.my"] = "http://longurl.org/services",
            ["doiop.com"] = "http://urlshortener.org",
            ["dopen.us"] = "http://longurl.org/services",
            ["drv2.com"] = "http://urlshortener.org",
            ["dwarfurl.com"] = "http://urlshortener.org",
            ["dz.ly"] = "http://urlshortener.org",
            ["earlme.com"] = "http://urlshortener.org",
            ["easyurl.net"] = "http://longurl.org/services",
            ["eepurl.com"] = "http://longurl.org/services",
            ["eg3.net"] = "http://urlshortener.org",
            ["ekey.us"] = "http://urlshortener.org",
            ["elurl.com"] = "http://urlshortener.org",
            ["eweri.com"] = "http://longurl.org/services",
            ["fa.by"] = "http://longurl.org/services",
            ["fat.ly"] = "http://urlshortener.org",
            ["fav.me"] = "http://longurl.org/services",
            ["fb.me"] = "http://longurl.org/services",
            ["fbshare.me"] = "http://longurl.org/services",
            ["ff.im"] = "http://longurl.org/services",
            ["fff.to"] = "http://fff.to/",
            ["fhurl.com"] = "http://urlshortener.org",
            ["fire.to"] = "http://longurl.org/services",
            ["firsturl.de"] = "http://longurl.org/services",
            ["firsturl.net"] = "http://longurl.org/services",
            ["flib.in"] = "http://urlshortener.org",
            ["flic.kr"] = "http://longurl.org/services",
            ["flq.us"] = "http://urlshortener.org",
            ["fly2.ws"] = "http://longurl.org/services",
            ["flyfrm.com"] = "N/A",
            ["fon.gs"] = "http://longurl.org/services",
            ["forit.org"] = "http://urlshortener.org",
            ["forwarding.clockwatchers.com"] = "http://forwarding.clockwatchers.com",
            ["freak.to"] = "http://longurl.org/services",
            ["fuseurl.com"] = "http://longurl.org/services",
            ["fuzzy.to"] = "http://longurl.org/services",
            ["fwd4.me"] = "http://urlshortener.org",
            ["fwib.net"] = "http://longurl.org/services",
            ["g.ro.lt"] = "http://urlshortener.org",
            ["gentleurl.net"] = "http://urlshortener.org",
            ["gizmo.do"] = "http://longurl.org/services",
            ["gl.am"] = "http://urlshortener.org",
            ["gli.im"] = "N/A",
            ["go.9nl.com"] = "http://longurl.org/services",
            ["go.ign.com"] = "http://longurl.org/services",
            ["go.usa.gov"] = "http://longurl.org/services",
            ["go2.st"] = "http://urlshortener.org",
            ["goo.gl"] = "http://longurl.org/services",
            ["good.ly"] = "http://urlshortener.org",
            ["gop.am"] = "http://urlshortener.org",
            ["goshrink.com"] = "http://longurl.org/services",
            ["gsfn.info"] = "N/A",
            ["gu.ma"] = "http://urlshortener.org",
            ["gurl.es"] = "http://urlshortener.org",
            ["hex.io"] = "http://longurl.org/services",
            ["hi2.com"] = "N/A",
            ["hiderefer.com"] = "http://longurl.org/services",
            ["hmm.ph"] = "http://longurl.org/services",
            ["hop.im"] = "http://urlshortener.org",
            ["hostviet.biz"] = "http://urlshortener.org",
            ["hotshorturl.com"] = "http://urlshortener.org",
            ["hotshr.com"] = "http://urlshortener.org",
            ["href.in"] = "http://longurl.org/services",
            ["href.to"] = "http://urlshortener.org",
            ["hsblinks.com"] = "http://longurl.org/services",
            ["htxt.it"] = "http://longurl.org/services",
            ["hub.tm"] = "http://urlshortener.org",
            ["huff.to"] = "http://longurl.org/services",
            ["hulu.com"] = "http://longurl.org/services",
            ["hurl.me"] = "http://urlshortener.org",
            ["hurl.ws"] = "http://urlshortener.org",
            ["icanhaz.com"] = "http://urlshortener.org",
            ["idek.net"] = "http://urlshortener.org",
            ["ikr.me"] = "http://urlshortener.org",
            ["ilix.in"] = "http://longurl.org/services",
            ["imfy.us"] = "http://urlshortener.org",
            ["in2s.us"] = "http://urlshortener.org",
            ["inturl.com"] = "http://urlshortener.org",
            ["ion.so"] = "N/A",
            ["is.gd"] = "http://urlshortener.org",
            ["it1.nl"] = "http://urlshortener.org",
            ["ito.mx"] = "http://urlshortener.org",
            ["its.my"] = "http://longurl.org/services",
            ["ix.lt"] = "http://longurl.org/services",
            ["j.mp"] = "http://longurl.org/services",
            ["jijr.com"] = "http://longurl.org/services",
            ["ju.nu"] = "http://urlshortener.org",
            ["kaano.info"] = "http://urlshortener.org",
            ["ki.tl"] = "http://urlshortener.org",
            ["kissa.be"] = "http://urlshortener.org",
            ["kiwiurl.com"] = "http://urlshortener.org",
            ["kl.am"] = "http://urlshortener.org",
            ["klck.me"] = "http://longurl.org/services",
            ["korta.nu"] = "http://urlshortener.org",
            ["krunchd.com"] = "http://urlshortener.org",
            ["krz.ch"] = "http://urlshortener.org",
            ["ks.gs"] = "N/A",
            ["kuerzer.de"] = "http://urlshortener.org",
            ["kxk.me"] = "http://urlshortener.org",
            ["l.pr"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["l9k.net"] = "http://longurl.org/services",
            ["lamped.co.uk"] = "http://urlshortener.org",
            ["lat.ms"] = "http://longurl.org/services",
            ["lawurl.com"] = "N/A",
            ["lb.vg"] = "http://urlshortener.org",
            ["liip.to"] = "http://longurl.org/services",
            ["liltext.com"] = "http://longurl.org/services",
            ["linkasa.com"] = "http://urlshortener.org",
            ["linkbee.com"] = "http://urlshortener.org",
            ["linkbun.ch"] = "http://longurl.org/services",
            ["linkfrog.net"] = "http://urlshortener.org",
            ["linkpeak.com"] = "http://urlshortener.org",
            ["liteurl.com"] = "http://urlshortener.org",
            ["liurl.cn"] = "http://urlshortener.org",
            ["lllll.im"] = "N/A",
            ["ln-s.net"] = "http://longurl.org/services",
            ["ln-s.ru"] = "http://longurl.org/services",
            ["lnk.by"] = "http://urlshortener.org",
            ["lnk.gd"] = "http://longurl.org/services",
            ["lnk.ms"] = "http://longurl.org/services",
            ["lnkd.in"] = "http://longurl.org/services",
            ["lnkurl.com"] = "http://longurl.org/services",
            ["lru.jp"] = "http://longurl.org/services",
            ["lt.tl"] = "http://longurl.org/services",
            ["lurl.no"] = "http://longurl.org/services",
            ["lymme.com"] = "http://urlshortener.org",
            ["macte.ch"] = "http://longurl.org/services",
            ["mash.to"] = "http://longurl.org/services",
            ["memurl.com"] = "http://urlshortener.org",
            ["merky.de"] = "http://longurl.org/services",
            ["metamark.net"] = "http://urlshortener.org",
            ["migre.me"] = "http://longurl.org/services",
            ["minify.me"] = "http://urlshortener.org",
            ["minilien.com"] = "http://urlshortener.org",
            ["minilink.org"] = "http://urlshortener.org",
            ["miniurl.com"] = "http://longurl.org/services",
            ["minu.me"] = "http://urlshortener.org",
            ["minurl.fr"] = "http://longurl.org/services",
            ["minyurl.net"] = "http://urlshortener.org",
            ["mke.me"] = "http://longurl.org/services",
            ["moby.to"] = "http://longurl.org/services",
            ["monbe.be"] = "N/A",
            ["moourl.com"] = "http://urlshortener.org",
            ["mrte.ch"] = "http://longurl.org/services",
            ["multiurl.com"] = "http://urlshortener.org",
            ["mylnk.us"] = "http://urlshortener.org",
            ["myloc.me"] = "http://longurl.org/services",
            ["myurl.in"] = "http://urlshortener.org",
            ["myurlz.com"] = "http://urlshortener.org",
            ["n.pr"] = "http://longurl.org/services",
            ["nbc.co"] = "http://longurl.org/services",
            ["nblo.gs"] = "http://longurl.org/services",
            ["ncane.com"] = "http://urlshortener.org",
            ["ne8.org"] = "http://urlshortener.org",
            ["netnet.me"] = "http://urlshortener.org",
            ["ni2.in"] = "http://urlshortener.org",
            ["ninjalink.com"] = "http://urlshortener.org",
            ["niy.me"] = "N/A",
            ["nn.nf"] = "http://longurl.org/services",
            ["no1.in"] = "http://urlshortener.org",
            ["normalurl.com"] = "http://urlshortener.org",
            ["not.my"] = "http://longurl.org/services",
            ["notlong.com"] = "http://urlshortener.org",
            ["nsfw.in"] = "http://longurl.org/services",
            ["nutshellurl.com"] = "http://longurl.org/services",
            ["nuurl.us"] = "http://urlshortener.org",
            ["nxy.in"] = "http://longurl.org/services",
            ["nyti.ms"] = "http://longurl.org/services",
            ["nznet.info"] = "N/A",
            ["o-x.fr"] = "http://urlshortener.org",
            ["oc1.us"] = "http://longurl.org/services",
            ["ohurl.com"] = "http://urlshortener.org",
            ["om.ly"] = "http://longurl.org/services",
            ["omf.gd"] = "http://longurl.org/services",
            ["omoikane.net"] = "http://longurl.org/services",
            ["on.cnn.com"] = "http://longurl.org/services",
            ["on.mktw.net"] = "http://longurl.org/services",
            ["onforb.es"] = "http://longurl.org/services",
            ["orkurl.com"] = "http://urlshortener.org",
            ["orz.se"] = "http://longurl.org/services",
            ["ow.ly"] = "http://urlshortener.org",
            ["p.gs"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["p.ly"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["parv.us"] = "http://urlshortener.org",
            ["pic.gd"] = "http://urlshortener.org",
            ["picsorlinks.com"] = "http://urlshortener.org",
            ["ping.fm"] = "http://longurl.org/services",
            ["piurl.com"] = "http://urlshortener.org",
            ["pli.gs"] = "http://longurl.org/services",
            ["pnt.me"] = "http://urlshortener.org",
            ["politi.co"] = "http://longurl.org/services",
            ["ponyurl.com"] = "http://urlshortener.org",
            ["post.ly"] = "http://longurl.org/services",
            ["pp.gg"] = "http://longurl.org/services",
            ["pr0n.net"] = "http://urlshortener.org",
            ["profile.to"] = "http://longurl.org/services",
            ["ptiturl.com"] = "http://urlshortener.org",
            ["pub.vitrue.com"] = "http://longurl.org/services",
            ["pwr.com"] = "http://urlshortener.org",
            ["qlnk.net"] = "http://urlshortener.org",
            ["qte.me"] = "http://longurl.org/services",
            ["qu.tc"] = "http://longurl.org/services",
            ["qurlyq.com"] = "http://urlshortener.org",
            ["quu.nu"] = "http://urlshortener.org",
            ["qwer.org"] = "http://urlshortener.org",
            ["qwx.si"] = "http://urlshortener.org",
            ["qy.fi"] = "http://longurl.org/services",
            ["r.im"] = "http://longurl.org/services",
            ["rb6.me"] = "http://urlshortener.org",
            ["rcez.info"] = "http://urlshortener.org",
            ["rde.me"] = "http://urlshortener.org",
            ["read.bi"] = "http://longurl.org/services",
            ["readthis.ca"] = "http://longurl.org/services",
            ["reallytinyurl.com"] = "http://longurl.org/services",
            ["redir.ec"] = "http://longurl.org/services",
            ["redir.ec"] = "http://urlshortener.org",
            ["redirects.ca"] = "http://longurl.org/services",
            ["redirx.com"] = "http://urlshortener.org",
            ["relurl.com"] = "http://urlshortener.org",
            ["retwt.me"] = "http://urlshortener.org",
            ["ri.ms"] = "http://longurl.org/services",
            ["rickroll.it"] = "http://longurl.org/services",
            ["riz.gd"] = "http://longurl.org/services",
            ["rt.nu"] = "http://longurl.org/services",
            ["ru.ly"] = "http://longurl.org/services",
            ["rubyurl.com"] = "http://longurl.org/services",
            ["rurl.org"] = "http://longurl.org/services",
            ["rww.tw"] = "http://longurl.org/services",
            ["s4c.in"] = "http://longurl.org/services",
            ["s7y.us"] = "http://urlshortener.org",
            ["safe.mn"] = "http://longurl.org/services",
            ["sameurl.com"] = "http://longurl.org/services",
            ["scrnch.me"] = "http://urlshortener.org",
            ["sdut.us"] = "http://longurl.org/services",
            ["sendtourl.com"] = "N/A",
            ["shar.es"] = "http://longurl.org/services",
            ["shink.de"] = "http://longurl.org/services",
            ["sho.li"] = "http://urlshortener.org",
            ["shoor.tk"] = "N/A",
            ["shorl.com"] = "http://urlshortener.org",
            ["short.ie"] = "http://longurl.org/services",
            ["short.to"] = "http://urlshortener.org",
            ["shorten.ws"] = "http://urlshortener.org",
            ["shortlinks.co.uk"] = "http://longurl.org/services",
            ["shortna.me"] = "http://urlshortener.org",
            ["shortner.com"] = "http://urlshortener.org",
            ["shorturl.com"] = "http://longurl.org/services",
            ["shout.to"] = "http://longurl.org/services",
            ["show.my"] = "http://longurl.org/services",
            ["shrinkify.com"] = "http://longurl.org/services",
            ["shrinkr.com"] = "http://longurl.org/services",
            ["shrt.fr"] = "http://longurl.org/services",
            ["shrt.st"] = "http://longurl.org/services",
            ["shrten.com"] = "http://longurl.org/services",
            ["shrunkin.com"] = "http://longurl.org/services",
            ["shrvl.com"] = "http://urlshortener.org",
            ["shw.me"] = "http://urlshortener.org",
            ["simurl.com"] = "http://longurl.org/services",
            ["simurl.com"] = "http://urlshortener.org",
            ["sl.ly"] = "http://urlshortener.org",
            ["slate.me"] = "http://longurl.org/services",
            ["slnk.me"] = "http://urlshortener.org",
            ["smal.ly"] = "http://urlshortener.org",
            ["smallr.com"] = "http://urlshortener.org",
            ["smlurl.info"] = "N/A",
            ["smrls.tk"] = "http://urlshortener.org",
            ["smsh.me"] = "http://longurl.org/services",
            ["smurl.lv"] = "http://urlshortener.org",
            ["smurl.name"] = "http://longurl.org/services",
            ["sn.im"] = "http://longurl.org/services",
            ["snipr.com"] = "http://longurl.org/services",
            ["snipurl.com"] = "http://urlshortener.org",
            ["snurl.com"] = "http://longurl.org/services",
            ["sp2.ro"] = "http://urlshortener.org",
            ["spedr.com"] = "http://longurl.org/services",
            ["sqze.it"] = "http://long-shore.com/expand",
            ["sra.li"] = "N/A",
            ["srnk.it"] = "http://urlshortener.org",
            ["srnk.net"] = "http://longurl.org/services",
            ["srs.li"] = "http://longurl.org/services",
            ["starturl.com"] = "http://urlshortener.org",
            ["sturly.com"] = "http://urlshortener.org",
            ["su.pr"] = "http://urlshortener.org",
            ["surl.co.uk"] = "http://longurl.org/services",
            ["surl.co.uk"] = "http://urlshortener.org",
            ["surl.hu"] = "http://longurl.org/services",
            ["t.co"] = "http://longurl.org/services",
            ["t.lh.com"] = "http://longurl.org/services",
            ["ta.gd"] = "http://urlshortener.org",
            ["tak.bz"] = "http://urlshortener.org",
            ["takeme.to"] = "http://urlshortener.org",
            ["tbd.ly"] = "http://longurl.org/services",
            ["tcrn.ch"] = "http://longurl.org/services",
            ["te.tl"] = "http://urlshortener.org",
            ["tgr.me"] = "http://longurl.org/services",
            ["tgr.ph"] = "http://longurl.org/services",
            ["thecow.me"] = "http://urlshortener.org",
            ["tighturl.com"] = "http://urlshortener.org",
            ["tiniuri.com"] = "http://longurl.org/services",
            ["tiny.cc"] = "http://urlshortener.org",
            ["tiny.ly"] = "http://longurl.org/services",
            ["tiny.pl"] = "http://urlshortener.org",
            ["tiny.tw"] = "N/A",
            ["tiny2go.com"] = "http://urlshortener.org",
            ["tinyftw.com"] = "http://urlshortener.org",
            ["tinylink.in"] = "http://longurl.org/services",
            ["tinyuri.ca"] = "http://longurl.org/services",
            ["tinyurl.com"] = "http://urlshortener.org",
            ["tl.gd"] = "http://longurl.org/services",
            ["tmi.me"] = "http://longurl.org/services",
            ["tnij.org"] = "http://longurl.org/services",
            ["tnw.to"] = "http://longurl.org/services",
            ["tny.com"] = "http://longurl.org/services",
            ["to.ly"] = "http://longurl.org/services",
            ["togoto.us"] = "http://longurl.org/services",
            ["totc.us"] = "http://longurl.org/services",
            ["toysr.us"] = "http://longurl.org/services",
            ["tpm.ly"] = "http://longurl.org/services",
            ["tr.im"] = "http://longurl.org/services",
            ["tra.kz"] = "http://urlshortener.org",
            ["trunc.it"] = "http://urlshortener.org",
            ["tuaurl.com"] = "http://urlshortener.org",
            ["turls.me"] = "http://urlshortener.org",
            ["tutz.me"] = "http://urlshortener.org",
            ["tw3.it"] = "http://urlshortener.org",
            ["tweak.tk"] = "http://urlshortener.org",
            ["tweez.me"] = "http://urlshortener.org",
            ["twhub.com"] = "http://longurl.org/services",
            ["twi.tl"] = "http://urlshortener.org",
            ["twirl.at"] = "http://longurl.org/services",
            ["twitclicks.com"] = "http://longurl.org/services",
            ["twitterto.com"] = "http://urlshortener.org",
            ["twitterurl.net"] = "http://urlshortener.org",
            ["twitterurl.org"] = "http://longurl.org/services",
            ["twiturl.de"] = "http://urlshortener.org",
            ["twurl.cc"] = "http://longurl.org/services",
            ["twurl.nl"] = "http://urlshortener.org",
            ["u.go2.me"] = "http://urlshortener.org",
            ["u.mavrev.com"] = "http://longurl.org/services",
            ["u.nu"] = "http://longurl.org/services",
            ["u76.org"] = "http://longurl.org/services",
            ["ub0.cc"] = "http://longurl.org/services",
            ["ulu.lu"] = "http://longurl.org/services",
            ["updating.me"] = "http://longurl.org/services",
            ["ur1.ca"] = "http://longurl.org/services",
            ["url.az"] = "http://longurl.org/services",
            ["url.co.uk"] = "http://longurl.org/services",
            ["url.ie"] = "http://urlshortener.org",
            ["url.in.it"] = "N/A",
            ["url.to.it"] = "http://urlshortener.org",
            ["url360.me"] = "http://longurl.org/services",
            ["url4.eu"] = "http://longurl.org/services",
            ["urlbit.us"] = "http://urlshortener.org",
            ["urlborg.com"] = "http://longurl.org/services",
            ["urlbrief.com"] = "http://longurl.org/services",
            ["urlcover.com"] = "http://urlshortener.org",
            ["urlcut.com"] = "http://longurl.org/services",
            ["urlenco.de"] = "http://longurl.org/services",
            ["urli.nl"] = "http://longurl.org/services",
            ["urlit.net"] = "http://urlshortener.org",
            ["urlminifier.com"] = "http://urlshortener.org",
            ["urlmorph.com"] = "http://urlshortener.org",
            ["urlpire.com"] = "http://urlshortener.org",
            ["urls.im"] = "http://longurl.org/services",
            ["urlx.ie"] = "http://longurl.org/services",
            ["urlxp.com"] = "http://urlshortener.org",
            ["urlzen.com"] = "http://longurl.org/services",
            ["usat.ly"] = "http://longurl.org/services",
            ["use.my"] = "http://longurl.org/services",
            ["ushort.co.uk"] = "http://urlshortener.org",
            ["ux.lv"] = "http://urlshortener.org",
            ["vani.sh"] = "http://urlshortener.org",
            ["vb.ly"] = "http://longurl.org/services",
            ["vgn.am"] = "http://longurl.org/services",
            ["viewista.com"] = "http://urlshortener.org",
            ["virl.com"] = "http://urlshortener.org",
            ["vl.am"] = "http://longurl.org/services",
            ["vm.lc"] = "http://longurl.org/services",
            ["vs0.net"] = "N/A",
            ["w0p.de"] = "http://urlshortener.org",
            ["w55.de"] = "http://longurl.org/services",
            ["wapo.st"] = "http://longurl.org/services",
            ["wapurl.co.uk"] = "http://longurl.org/services",
            ["webalias.com"] = "http://urlshortener.org",
            ["weshort.in"] = "http://urlshortener.org",
            ["whit.me"] = "http://urlshortener.org",
            ["widg.me"] = "N/A",
            ["wipi.es"] = "http://longurl.org/services",
            ["wp.me"] = "http://longurl.org/services",
            ["wurl.ca"] = "http://urlshortener.org",
            ["wurl.ws"] = "http://urlshortener.org",
            ["wva.gd"] = "http://urlshortener.org",
            ["wwb.in"] = "http://urlshortener.org",
            ["x.co"] = "http://app.x.co/",
            ["x.se"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["x.vu"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["x2t.com"] = "http://urlshortener.org",
            ["xa.ly"] = "http://xa.ly/",
            ["xaddr.com"] = "http://urlshortener.org",
            ["xiy.net"] = "http://urlshortener.org",
            ["xpnd.it"] = "http://long-shore.com/expand",
            ["xr.com"] = "http://urlshortener.org",
            ["xrl.in"] = "http://longurl.org/services",
            ["xrl.us"] = "http://longurl.org/services",
            ["xurl.es"] = "http://longurl.org/services",
            ["xurl.jp"] = "http://urlshortener.org",
            ["y.ahoo.it"] = "http://longurl.org/services",
            ["yatuc.com"] = "http://longurl.org/services",
            ["ye.pe"] = "http://longurl.org/services",
            ["yep.it"] = "http://urlshortener.org",
            ["yfrog.com"] = "http://longurl.org/services",
            ["yhoo.it"] = "http://longurl.org/services",
            ["yi.pe"] = "N/A",
            ["yiyd.com"] = "http://longurl.org/services",
            //["youtu.be"] = "http://longurl.org/services",
            ["yuarel.com"] = "http://longurl.org/services",
            ["yvy.me"] = "http://yvy.me/",
            ["z.pe"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["z0p.de"] = "http://longurl.org/services",
            ["zapit.nu"] = "http://urlshortener.org",
            ["zeek.us"] = "http://urlshortener.org",
            ["zi.ma"] = "http://longurl.org/services",
            ["zi.mu"] = "http://longurl.org/services",
            ["zipmyurl.com"] = "http://longurl.org/services",
            ["ziprl.com"] = "http://urlshortener.org",
            ["zkracene.cz"] = "http://zkracene.cz/",
            ["zolp.net"] = "N/A",
            ["zud.me"] = "http://longurl.org/services",
            ["zurl.ws"] = "http://urlshortener.org",
            ["zwap.to"] = "http://urlshortener.org",
            ["zxc9.com"] = "http://urlshortener.org",
            ["zz.gd"] = "http://longurl.org/services",
            ["zzang.kr"] = "http://longurl.org/services",
            ["zzz.ee"] = "http://urlshortener.org",
            ["joturl.com"] = "http://www.joturl.comS",
            ["co.nr"] = "http://www.freedomain.co.nr/",
        }.ToImmutableDictionary();

        public static readonly LinkfilterMatcher UrlShortenerRegex = new LinkfilterMatcher(UrlShorteners.Keys);
    }
}