// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModCore.Services;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ModCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210708201445_GuildConfig")]
    partial class GuildConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ModCore.Entities.GuildConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("LogChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_channel_id");

                    b.Property<long>("MuteRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("mute_role_id");

                    b.Property<string>("Prefix")
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<bool>("SpellingHelperEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("spelling_helper_enabled");

                    b.HasKey("GuildId");

                    b.ToTable("guild_config");
                });
#pragma warning restore 612, 618
        }
    }
}
