// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModCore.Services;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ModCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210708211010_TimerDispatch")]
    partial class TimerDispatch
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ModCore.Entities.GuildConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("LogChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_channel_id");

                    b.Property<long>("MuteRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("mute_role_id");

                    b.Property<string>("Prefix")
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<bool>("SpellingHelperEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("spelling_helper_enabled");

                    b.HasKey("GuildId");

                    b.ToTable("guild_config");
                });

            modelBuilder.Entity("ModCore.Entities.TimerEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("Dispatch")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dispatch");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("timer_type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("TimerEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
