<Project>
  <PropertyGroup>
    <SharedSettingsFile>$(MSBuildThisFileDirectory)../.env</SharedSettingsFile>
    <SharedSettingsSampleFile>$(MSBuildThisFileDirectory)../example.env</SharedSettingsSampleFile>
  </PropertyGroup>

  <Target Name="CreateSharedSettingsFile"
          BeforeTargets="AssignTargetPaths"
          Condition="'$(Configuration)' == 'Debug'">

    <Copy SourceFiles="$(SharedSettingsSampleFile)"
          DestinationFiles="$(SharedSettingsFile)"
          Condition="!Exists('$(SharedSettingsFile)') And Exists('$(SharedSettingsSampleFile)')" />

    <Error Text="Missing .env and example.env in solution root."
           Condition="!Exists('$(SharedSettingsFile)') And !Exists('$(SharedSettingsSampleFile)')" />

    <ItemGroup>
      <ContentWithTargetPath Include="$(SharedSettingsFile)"
                             TargetPath=".env"
                             CopyToOutputDirectory="PreserveNewest"
                             Condition="Exists('$(SharedSettingsFile)')" />
    </ItemGroup>
  </Target>
</Project>